src/algo.rs
src/node.rs
src/result.rs
tests/simple_child.rs

Revert #2 and https://github.com/vislyhq/stretch/pull/87
The test from #2 is still present and still successful.
With those two PRs, the value returned for location is the absolute value. Without, the value is relative to its parent.
The test expect the value to be relative, as for example in this test:
https://github.com/DioxusLabs/stretch/blob/02033c0e8f52c9d12c40557804162eadd3f8a3a2/tests/generated/flex_basis_slightly_smaller_then_content_with_flex_grow_large_size.rs#L77-L84
where `node10` has a location.x of 0 even though its parent `node1` has a location.x of 80
This PR makes it work OK for Bevy again

change layout back to be relative

---

README.md

This is redundant to LICENSE.md.
First half of #10.

Remove license from README

---

Cargo.toml

Closes #18.
The `[badges]` section in Cargo.toml included a `circle-ci` badge which is not applicable to this repository. It also included a `maintenance` status, but this is currently not used on crates.io, so I removed it as well ([Docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section)).

Remove badges section in Cargo.toml

---

src/forest.rs
src/lib.rs
src/node.rs

Closes #21.
This PR adds `#![forbid(unsafe_code)]` on a crate level.
It also removes unnecessary usages of the `unsafe` keyword in the `remove_child` function:
- https://github.com/DioxusLabs/stretch/blob/c267e6296caea4217a498935ccaf57483b5c9235/src/forest.rs#L160-L163
- https://github.com/DioxusLabs/stretch/blob/c267e6296caea4217a498935ccaf57483b5c9235/src/node.rs#L156

Forbid unsafe code

---

.github/linters/.markdown-lint.yml
.github/workflows/ci.yml

Closes #13.
This adds a new step to the CI workflow which runs [markdownlint](https://github.com/DavidAnson/markdownlint).
I copied it [from bevy](https://github.com/bevyengine/bevy/blob/ae580e58dd1d8539e26a44a4d428e1aa45a3d6f9/.github/workflows/ci.yml#L184-L198) for the most part, with some adjustments:
- Added a `name` for consistency with the other CI steps.
- Removed dependency on `check-missing-examples-in-docs`, because we don't have that.
- Replaced the `.markdown-lint.yml` rule template with the one from the [official templates](https://github.com/github/super-linter/blob/main/TEMPLATES/.markdown-lint.yml), so that it links to the rules and provides some examples. I commented out the example rules, although I'm not sure if that was necessary due to the `---` usage at the start of …

Add markdownlint to CI action

---

.github/workflows/ci.yml
src/sys.rs

Closes #32.
This PR adds two new jobs to the CI workflow to `cargo check` and `cargo test` with the `--no-default-features` flag. Currently this has mainly the effect of enabling `no_std`.
Notably these currently throw errors, which just highlights the need to include it in CI.
I'm not sure if I'm able to resolve these errors as I've never worked with `no_std` before, but I can certainly try :)
Side note: Why do we have both `cargo check` and `cargo test` jobs? Wouldn't `cargo test` always fail if `cargo check` fails?
**TODO**:
⚠️ **This is a breaking change!** (I think) ⚠️
The fixes to the no-default-feature configuration is probably a breaking change.

Add CI jobs for checking and testing with no default features

---

Cargo.toml
LICENSE.md

- The LICENSE incorrectly listed all contributions as belonging to Visly.
- The cargo metadata for the license was misconfigured.
- Fixes #10.
- Clarify the state of the license: copyright remains with the open source contributors, who license it under MIT
- Fix the metadata in Cargo.toml

Fix license information

---

README.md

- `stretch2` users should know where to go for future development
- Mark the crate as deprecated in the README (which will be displayed on crates.io)
- link to the tentative future URL (following the conclusion of #42)

Mark `stretch2` as deprecated

---

Cargo.toml

- Author was still listed as team member from visly
- He is unlikely to respond to emails asking him about maintenance of `stretch2` ;)
- Update crate authors correctly

Update authors field

---

.github/pull_request_template.md

The PR template was unclear or overly verbose in places
The changes here were inspired by the helpful feedback in https://github.com/bevyengine/bevy/pull/4815

Make PR template clearer and shorter

---

Cargo.toml
RELEASES.md

- some dependencies (like serde) were out of date
- this can have correctness or performance implications
- more importantly, this can cause frustrating dependency duplication in upstream consumers, bloating compile times and executable size
- our version numbers were specified overly precisely, pinning minor versions
- this forces us to update dependencies manually too frequently, whenever bug fixes are released
- consumers who want to prioritize supply chain security can use [cargo patch](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html) to pin the transitive dependencies themselves.

Bump version numbers of dependencies

---

Cargo.toml
RELEASES.md
src/geometry.rs
src/number.rs
src/style.rs

- these features are not correctly additive: enabling both features at once will break compilation
- Rust analyzer is correctly complaining about duplicate attributes
- these features are poorly motivated
- presumably this is for cross-language serialization?
- renaming like this is easily handled by external batch processing if needed 
If you were using these features, rename your generated serialization files manually (and get in touch to explain why you cared).

Remove serde_camel_case and serde_kebab_case features

---

.github/pull_request_template.md

- the Migration Guide section of the PR template is redundant to RELEASES,md
- we should have a single source of truth

Remove migration guide from PR template

---

Cargo.toml
RELEASES.md
src/sys.rs

- alloc and std were not compatible
- this led to some very noisy error messages in rust-analyzer
- fixes #85
- `std` will be preferred over `alloc` if both are present

Make alloc and std compatible features

---

RELEASES.md
src/result.rs

- this code is marked dead, but is written to with actual values
- based on examination of the code, this appears to actually be useful information about the relative z-ordering of the fields
- make this pub, which eliminates the need for the `#[allow(dead_code)]` annotation
- add basic docs
- fixes #93

Make order field of `Layout` pub

---

src/node.rs

- because we're now using a [bump allocator](https://os.phil-opp.com/allocator-designs/) in the form of an `AtomicUsize`, freed memory is not actually freed
- there is called in several places but is actually a no-op
- remove this method completely, changing nothing but simplifying several pieces of code

Remove Allocator::free

---

src/forest.rs

- the `Forest::mark_dirty` method was quite confusing and hard to read
- `mark_dirty_impl` renamed to `mark_dirty_recursive`
- the changes done to each `NodeData` have been moved to a simple inlined method on `NodeData`
- basic docs have been added to explain the work that is being done

Refactor Forest::mark_dirty for clarity

---

RELEASES.md
src/prelude.rs
src/style.rs

Just like in #111, this code is completely dead.
It should be removed, rather than misleading users.

Remove dead Overflow type

---

src/flexbox.rs
src/forest.rs
src/geometry.rs
src/layout.rs
src/node.rs
src/number.rs
src/sys.rs

Fixes #103 
I've just naively added `#[must_use]` and all static methods I could find, which also include constructors. I don't know if that is the correct approach, so please let me know.

Add `#[must_use]` to all static methods

---

src/flexbox.rs

All of the other imports use direct import styles. Since cleaning up the feature strategy for `sys.rs` this clearer style should work fine for the imports from there too.

Use consistent import style in flexbox.rs

---

RELEASES.md
src/flexbox.rs
src/sys.rs

Several internal types were publicly exposed. This is confusing and noisy, and limits our ability to make changes to implementation details in minor releases.
They are now pub(crate) instead.

Stop leaking internal types in public interface

---

src/indexmap.rs

Some code within `indexmap` is unused, but should be kept around for now. See discussion in #108.
However, this is showing up as warnings in CI. Adding these annotations should silence that.

Add allow(unused_code) annotations to methods in indexmap

---

CONTRIBUTING.md
Cargo.toml
RELEASES.md
scripts/gentest/Cargo.toml
scripts/gentest/src/main.rs
scripts/gentest/test_base_style.css
scripts/gentest/test_helper.js
src/flexbox.rs
src/style.rs
tests/generated/min_height.rs
tests/generated/min_width.rs
tests/generated/percentage_flex_basis_cross_min_height.rs
tests/generated/rounding_flex_basis_flex_grow_row_prime_number_width.rs
tests/generated/rounding_flex_basis_flex_grow_row_width_of_100.rs
tests/generated/rounding_flex_basis_overrides_main_size.rs
tests/generated/rounding_fractial_input_1.rs
tests/generated/rounding_fractial_input_2.rs
tests/generated/rounding_fractial_input_3.rs
tests/generated/rounding_fractial_input_4.rs

Comparing with a browser implementation is the simplest way to ensure results will match what is expected. This can't be done by fuzzing or prop testing as both would mean recoding a flexbox implementation in tests to generate the assertions to validate the "random" values used.
#141 removed the gentlest script which ensure the tests generated from Chrome are up to date. I strongly disagree with this.
Fixes #65 
* I re-added and fixed the gentest script
* I regenerated the tests. There was a few errors that are probably due to changes in Chrome impl since the last time the tests were run (most likely 3 years ago?)
* rounding of fractional values has been simplified
* do not use the minimum size to compute the basis value for the size. this caused an issue when specifying a growth factor …

restore and fix gentest

---

.gitattributes

The generated tests and benchmarks add a lot of noise when reviewing PRs.
Their diffs should be hidden by default.
This PR adds a `.gitattribute` file that marks the folders `tests/generated` and `benches/generated` as `linguist-generated=true`. This will a) exclude them from the GitHub language stats and b) hide their diffs by default ([Docs](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github)).
We first discussed removing the generated tests completely in #133.
However, they add a lot of value to make sure that we are fully compatible with the browser flexbox spec. Thus, they were added back with #145.
We also discussed to not commit the generated files to the repository, but generating them requires installation of …

Mark generated files as lunguist-generated

---

src/indexmap.rs

`#[allow(dead_code)]` is the correct lint to use here, so lets start using it.
Noticed @alice-i-cecile did this change in #144, this just does the same in isolation. Feel free to close this one out if we'd rather just merge that one.

Replace `#[allow(unused_code)]` with `#[allow(dead_code)]` in `indexmap.rs`

---

scripts/gentest/src/main.rs

Fixes #45 
This fixes the error message, but I'm not able to get the gentest to run correctly from only installing this. Do we have other dependencies that needs to be installed?
@mockersf Was there other things you did to get it to produce an output?

Improve error message when `chromedriver` is not installed

---

src/style.rs

This PR removes the rename serde field attribute from the `Display` variants so that the serialized and deserialized values are consistent with the other style enum variants.

Remove serde renames from Display

---

RELEASES.md
examples/basic.rs
examples/nested.rs
src/error.rs
src/lib.rs
src/node.rs
src/prelude.rs

Replaces `taffy::Error` with `taffy::NodeNotFoundError` to make code much more legible. Also adds `taffy::ChildOperationError` so that `remove_child_at_index`, `replace_child_at_index`, and `child_at_index` can return an error instead of panicing.
Fixes #100 #104
I'm not happy with the name of `ChildOperationError`. It feels a little vague to me. Is it fine, or is there possibly a better name for it?
Also, I'm not sure I should have flattened NodeNotFoundError into a tuple struct.

Improve Errors

---

src/node.rs

This `TODO` was fixed in #152, but the note was left unremoved. This cleans that up

Remove solved todo note

---

RELEASES.md
src/node.rs

Fixes #146. This was much more straightforward than I was concerned it might be, we just needed to add a trait bound. This will unblock #27.

Make `MeasureFunc` Send and Sync

---

.github/ISSUE_TEMPLATE/bug_report.md
src/flexbox.rs
src/forest.rs
src/math.rs
src/style.rs

I'm trying to start contributing to this project and fixing comment typos seemed like a good way to do so :)
Discuss any context that may be needed for reviewers to understand the changes you've made.
This may include related issues, previous discussion, or links to documentation or code.
I'm not sure if this is common, but maybe it would be cool to have some spell checking in the CI pipeline. Specially since all of the typos were caught by a VSCode extension, so it should be easy to automate.
VSCode also removed some whitespaces when saving. I don't think this will cause any issues, but let me know!

Fix comment typos

---

src/math.rs

The implementations of `MaybeMath` used `#[allow(clippy::manual_map)]`.
This PR removes this lint suppression and applies `cargo clippy --fix` to use `map` instead of the `match` statement.
The original implementation justified the lint suppression as follows:
> The logic here is subtle and critical;
> explicit match statements make it more clear what's going on
Do the explicit map statements really make it more clear what's going on?
Personally, I think the `map` statements are also clear.
If we're unsure if something works we should add unit tests instead.
I think it's good to suppress as little lints as possible.

Remove manual map implementation in `MaybeMath`

---

src/geometry.rs
src/style.rs

A tiny step towards #92, but mostly I need to see where things are breaking when working on #160 and building unit-test helps.
Not quite sure if these are considered good tests as they feel a tiny bit arbitrary in terms of which magical numbers to test for, so any feedback is welcome :)

Add unit-tests to `resolve`

---

RELEASES.md
src/forest.rs
src/node.rs
tests/measure.rs
tests/node.rs

- Fixes #180
- Added `taffy::node::Taffy.new_leaf()` which allows the creation of new leaf-nodes without having to supply a measure function
- Renamed `taffy::node::Taffy.new_leaf()` -> `taffy::node::Taffy.new_leaf_with_measure()`

Add and cleanup new leaf-nodes methods

---

CONTRIBUTING.md

As discussed in #179, this adds a short guideline for how to write and organise tests within `taffy`
Mostly to help people such as myself that are unfamiliar with this, but also just to ensure consistency and consensus through the project. 
Also, we need a lot of tests to any way we can make it simpler to contribute on the testing side is a win!
I don't want it to be too terse or verbose, so please comment on phrasing ++

Add guideline to write tests

---

RELEASES.md
src/flexbox.rs
src/geometry.rs
src/layout.rs
src/lib.rs
src/node.rs
src/resolve.rs
src/style.rs

One more step towards #92
This PR is a bit of a mixed bag, so let me know if I should split it up. 
The objective of this PR is to set us up so that we can start testing the flexbox algorithm.
While trying to cover the `compute_constants()` in tests, I discovered the code needed a bit refactoring and massaging in order to actually be testable. 
Here I realized that the different `resolve()` methods can be abstracted to a "Resolve" trait, and following the convention of `MaybeMath`, we now have `MaybeResolve` and `ResolveOrDefault`. 
These traits encapsulate behaviour where we need to resolve from a potentially context-dependent size / dimension into a context-independent size / dimensions. In other words:
1. A size can be one (`Dimension`) or two dimensional (`Size<Dimension>` / …

Unit test `compute_constants()`

---

benches/complex.rs
examples/basic.rs
examples/nested.rs
scripts/gentest/src/main.rs
src/node.rs
tests/measure.rs
tests/relayout.rs
tests/root_constraints.rs
tests/simple_child.rs

Fixes #189 
I haven't made any changes to the generated code nor it's generation-script, so it will keep producing leaf-nodes using `new_with_children()` but I reckon that is acceptable.

Cleanup `new_with_children()` uses

---

src/style.rs

Had some confusion when I was using this library due to the wording being "positive" and not "nonnegative," thought that 1 must mean no stretching instead of 0.
0 is not positive.

Clarify documentation

---

Cargo.toml

Remove unused dependencies
None of these dependencies are even referenced anywhere as far as I can:
- Running ripgrep against the crate names only turns up results in Cargo.toml
- Searching for "use crate_name" in git history shows that uses have been removed
Specifically:
- `typenum` was used with an older version of ArrayVec, and isn't needed now ArrayVec is using const generics
- `hash32` and `hash32` derive were used for the custom forest implementation which has been replaced
- Usage of `hashbrown` was removed in 2019. We're not currently using any HashMaps (unless SlotMap counts), but if we were too then it would make sense to use the one from std/alloc which is now based on hashbrown anyway.
I've run `cargo build`, `cargo test`, and `cargo bench` and all still run fine on my …

Remove unused deps: hashbrown, hash32, typenum

---

deny.toml

CI is complaining about errors in our license-checking CI following #210.
https://github.com/DioxusLabs/taffy/runs/7567032612?check_suite_focus=true
I've removed those, so then CI will pass again 🎉 I'm also going to configure the repo to make sure that that check is required to merge.

Remove unused licenses from DENY.tonl list

---

.github/workflows/ci.yml
scripts/gentest/src/main.rs
src/node.rs

Clippy generated a bunch of warnings for the `scripts/gentest` project in the workspace.
This PR fixes those warnings and modifies the CI workflow to run Clippy on the entire workspace. This forces us to keep all the code clean and tidy.

Run Clippy CI on the entire workspace

---

Cargo.toml
benches/big_tree.rs
benches/complex.rs
src/lib.rs
src/randomizable.rs

Closes #128.
This PR aims to add more robust benchmarks that deal with much larger trees to get a better comparison point for performance improvements.
This PR generates large trees of 100,000 nodes via pseudo-random generation.
One benchmark uses a very flat hierarchy, the other one has a branching factor of 7 so it goes deeper (about 6).
I also increased the sample size of the other benchmarks from 100 to 200 to reduce noise.
The current benchmarks worked with rather small trees and are very noisy. We can also think about increasing the sample size to improve the stability of these benchmarks.
- The "deep" benchmark is a _lot_ slower than the "flat" benchmark, even though the depth should only be about log_7(100_000) ~ 6. The flat benchmark takes < 5 ms and the deep benchmark almost 3 …

Add more robust benchmarks

---

src/node.rs

Fixes #250. Also added a unit test.

Fix calling set_measure on a node that didn't previously have a measure func

---

src/compute/mod.rs
src/data.rs
src/node.rs
src/tree.rs

- Cargo semver picked up that the signature of `Taffy.mark_dirty()` had changed from `mark_dirty(&self, node: Node) -> TaffyResult<()>` to `mark_dirty(&self, node: Node, is_dirty: boolean)`. This seems like a needless breaking change which actually makes the API worse, so this PR undoes it.
- It also gets rid of the `is_dirty` flag internally (as it wasn't being read except to respond to the public `.dirty()` method). `mark_dirty()` now simply clears all cache entries, and `.dirty()` returns true if all cache entries are `None`.
- Finally it corrects an issue where the wrong `mark_dirty` method was being called (there was both a trait method and an inherent impl), which would cause the marking to happen only to the specified node, and not recursively up the tree.

Change signature of mark_dirty method to match taffy 0.1

---

Cargo.toml
deny.toml

Once this PR is merged, I intend to release taffy 0.2.
Testing the release currently fails:
> alice@pop-os:~/Documents/Code/taffy$ cargo publish --dry-run
>     Updating crates.io index
>    Packaging taffy v0.2.0 (/home/alice/Documents/Code/taffy)
> error: failed to prepare local package for uploading
> 
> Caused by:
>   failed to select a version for the requirement `taffy = "^0.2.0"`
>   candidate versions found which didn't match: 0.1.0
>   location searched: crates.io index
>   required by package `taffy v0.2.0 (/home/alice/Documents/Code/taffy)`
Removing the explicit version causes this to pass correctly. It's currently unclear how this worked before. EDIT: it never has :(

Don't specify explicit version for dev-dependencies

---

RELEASES.md
src/compute/flexbox.rs
src/compute/mod.rs
src/node.rs
src/tree.rs

The current approach of returning `&[Node]` only works if the tree stores the children contiguously. Returning an iterator allows the tree to completely abstract the method of storage. 
Related to #222 
I'm not completely sure about the lifetimes for the iterator. I didn't want to force a copy when the children actually are stored contiguously so I used a GAT to allow returning a borrowing iterator. However, this now ties the lifetime of the iterator to the lifetime of the tree. However, I think this is correct but thought I'd mention it in acse anyone can think of a situation where this wouldn't be the case.
I'm not sure if this change is necessary until work on implementing another layout system, such as [morphorm](https://github.com/vizia/morphorm), into taffy …

Return iterator for children for `LayoutTree`

---

src/lib.rs

Fixes #263
We should potentially backport and release this in a `0.2.1` release, along with #262? I'm not sure how much effort the actual release process is, but the backport should be straightforward.

Re-export compute::compute_layout at the top level

---

src/debug.rs

Small change but I thought it might be useful to better visualise the tree when debug printing. As an example:
```
TREE
└── [x: 0, y: 0, width: 50, height: 20]
├── [x: 0, y: 0, width: 20, height: 20]
│   ├── [x: 0, y: 0, width: 7, height: 20]
│   ├── [x: 7, y: 0, width: 7, height: 20]
│   └── [x: 13, y: 0, width: 7, height: 20]
└── [x: 30, y: 0, width: 20, height: 20]
```
(this looks even better with a font that supports ligatures)
I was going to add the node number but it's not accessible. I could probably add one using a counter passed to the recursive `print_node` function but I don't know if that would be desired or not.

Make tree debug printing more readable

---

RELEASES.md
src/compute/leaf.rs
tests/border_and_padding.rs

Fixes:
If the top and bottom border and padding fields are set to percentage values then they are multiplied by `available_space.width`, instead of `.height`:
```rust
use taffy::prelude::*;
fn main() {
let mut taffy = Taffy::new();
let node = taffy.new_leaf(Style {
padding: Rect {
left: LengthPercentage::Percent(1.0), 
top: LengthPercentage::Percent(1.0),
..Rect::zero()
},
..Default::default()
}).unwrap();
taffy.compute_layout(
node, 
Size { width: AvailableSpace::Definite(200.0),  height: AvailableSpace::Definite(100.0) }
)
.ok();
println!("{:?}", taffy.layout(node).unwrap().size);   
}
```
output:
```
Size { width: 200.0, height: 200.0 }
```
should be:
```
Size { width: 200.0, height: 100.0 }
```

Vertical border and padding percentage values are multiplied by available_space.width

---

RELEASES.md
src/compute/leaf.rs
tests/border_and_padding.rs

All percentage padding/border values (including vertical ones) resolve against the node's inline size (width in horizontal writing modes) as per the CSS spec. See: https://developer.mozilla.org/en-US/docs/Web/CSS/padding#values
Reverts half of https://github.com/DioxusLabs/taffy/pull/273

Revert "Resolve vertical percentage padding/border against node height"

---

RELEASES.md
benches/generated/grid_min_content_flex_column.rs
benches/generated/grid_min_content_flex_row.rs
benches/generated/mod.rs
src/compute/flexbox.rs
src/compute/mod.rs
src/data.rs
test_fixtures/grid_min_content_flex_column.html
test_fixtures/grid_min_content_flex_row.html
tests/generated/grid_min_content_flex_column.rs
tests/generated/grid_min_content_flex_row.rs
tests/generated/mod.rs
tests/measure.rs

Nesting a flexbox row inside a grid column with a min-content width was giving incorrect results.
This was discovered in testing Grid/Flexbox interaction, although I believe it was a pre-existing bug in the Flexbox implementation that was exposed by the Grid implementation implementing `min-content`.
- Compute flex children's "minimum size" according to the spec
- Updated cache implementation to avoid thrashing the cache with the new implementation (which happens because we now sometimes need to size a node under both a min-content and a max-content constraint). This bumps the cache size from 4 to 5. I think a similar change would be required for decent Grid perf anyway (we just haven't started measuring this yet).
- Added tests to cover failing cases.
- Updated measure.rs test values …

Fix sizing of flexbox nodes under a min-content constraint

---

src/compute/flexbox.rs

Optimise and clarify code. I'l be honest, I don't fully understand why this works the way it does. But this PR adds some explanation, and also replaces a call to measure the child with the stored result of an earlier call to do the same.

Avoid call to measure child by reusing the already-computed resolved_minimum_size

---

.github/workflows/ci.yml
Cargo.toml
README.md
RELEASES.md
benches/generated/mod.rs
examples/grid_holy_grail.rs
scripts/gentest/src/main.rs
src/compute/mod.rs
src/debug.rs
src/geometry.rs
src/lib.rs
src/prelude.rs
src/style/dimension.rs
src/style/mod.rs
src/style_helpers.rs
src/sys.rs
tests/generated/mod.rs

Without this, development becomes difficult as development tools (from Rust Analyzer to cargo test) won't see modules by default. We don't intend to publish a new stable release until grid support is tested and ready anyway.

Make CSS Grid feature a default feature

---

docs/style-properties.md
src/style/mod.rs

Document the size of each style as a first step in thinking about optimising memory use, and as a useful data point for when thinking about how we might want to split up the `Style` struct.
IMO most interesting thing to come out of this is how big `LengthPercentage`, `LengthPercentageAuto`, and `Dimension` are (8 bytes each). These would be the obvious thing to target if we wanted optimise memory usage:
- I believe we could shave `72` bytes out of the total `344` by switching these types to use `NonNaNf32` rather than `f32` (enabling niche optimisation on the containing enum).
- We could also consider creating a custom `f24` format (truncated `f32`) if we really wanted to.

Add style size test + update style-properties.md with sizes

---

src/compute/grid/mod.rs

Basically fixes the usage of the wrong variable
https://github.com/DioxusLabs/taffy/issues/204#issuecomment-1369326456

Fix using column variable for row calculation

---

docs/style-properties.md

f32 wasn't in line with aspect_ratio over here: https://github.com/DioxusLabs/taffy/blob/main/src/style/mod.rs

Align aspect ratio type with code

---

Cargo.toml
README.md
benches/big_tree.rs
benches/yoga_helpers.rs
deny.toml
src/style/dimension.rs

Fixes #166
Allows our full benchmark suite to be run againt Yoga as well as Taffy
Taffy is slightly ahead on the ` yoga 'huge nested'` benchmark with 100,000 nodes. Yoga is slightly ahead on the `big trees (wide)` benchmark with 100,000 nodes. Otherwise yoga and Taffy are basically neck and neck on pretty much all of these.
| Benchmark          | Node Count | Depth | Yoga ([ba27f9d]) | Taffy ([9059647]) |
| ---                | ---        | ---   | ---              | ---               |
| yoga 'huge nested' | 1,000      | 3     | 411.42 µs        | 275.47 µs         |
| yoga 'huge nested' | 10,000     | 4     | 3.9882 ms        | 3.9409 ms         |
| yoga 'huge nested' | 100,000    | 5     | 46.117 ms        | 32.458 ms         |
| big trees (wide)   | 1,000      | 1     | 750.75 µs …

Implement head-to-head benchmarks against Yoga

---

src/compute/grid/mod.rs
src/compute/grid/track_sizing.rs
src/compute/grid/types/grid_item.rs
src/compute/grid/types/grid_track.rs
src/style/grid.rs

Improve performance of the CSS Grid algorithm. This one was the last one on my list of obvious optimisations.
These changes seem to provide modest but consistent improvements (~10%) for our existing benchmark. It also leads to more significant improvements (~50%) for the case where:
- The container size is known
- All columns are either a fixed (absolute or percentage) size or `minmax(0, 1fr)`
The 6500 node "deep" benchmark is down to ~8ms with this PR and with all `minmax(0, 1fr)` (and ~18ms with a random mix of track types). This is quite a common use case "I want N evenly sized row or columns", so this represents quite a useful fast path.

Grid: selectively rerun track sizing

---

src/style_helpers.rs

This a tiny change to use concrete types instead of generic types for the arguments of the `minmax()` function because only those specific concrete types are valid anyway.

Only accept track sizing functions as input to the minmax() helper

---

RELEASES.md
benches/generated/flex_column_relative_all_sides.rs
benches/generated/flex_row_relative_all_sides.rs
benches/generated/grid_relative_all_sides.rs
benches/generated/mod.rs
src/compute/flexbox.rs
test_fixtures/flex_column_relative_all_sides.html
test_fixtures/flex_row_relative_all_sides.html
test_fixtures/grid_relative_all_sides.html
tests/generated/flex_column_relative_all_sides.rs
tests/generated/flex_row_relative_all_sides.rs
tests/generated/grid_relative_all_sides.rs
tests/generated/mod.rs

Fixes https://github.com/bevyengine/bevy/issues/7488
For a `position: relative` node, `bottom` should be ignored if `top` is set and `right` should be ignored if `left` is set. But for flexbox children, Taffy was applying both instead.
None. This is a tiny fix and should be uncontroverisal.

Fix inset being incorrectly applied to `position:relative` flex items when both insets were set in a given axis

---

benches/helpers/mod.rs

A module that should have been public was private causing the benchmark compilation to fail

Fix yoga benchmark compilation

---

src/compute/flexbox.rs

Improve flexbox performance.
Seeing a 20% improvement on "deep" benchmarks here. 30% on Yoga's "huge nested" benchmark which happens to use fixed sizes on pretty much every node.
In future it would nice to make this work in scenarios where only one axis has a fixed size by making `measure_node` take an axis as a parameter. But that would require a big refactor whereas this is a simple change.

Avoid performing layout when computing size and size is known from styles

---

Cargo.toml
src/style/mod.rs
src/style_helpers.rs
tests/serde.rs

As per https://github.com/DioxusLabs/taffy/pull/363#issuecomment-1427190436, Taffy v0.3.x breaks the ability to deserialize nested partial values (e.g. specifying only two of the 4 inset properties):
- This PR fixes that ability + adds a test for it
- It also implements the style helpers for `Line<T>`. That turned out not to be necessary for this fix, but it's useful functionality to have anyway.

Fix deserialize partial values with serde

---

src/style/alignment.rs

Fixes a small spelling mistake in alignment's comments.

Spelling mistake in alignment's comments

---

src/compute/mod.rs
test_fixtures/display_none_only_node.html
test_fixtures/grid_display_none_fixed_size.html
tests/generated/display_none_only_node.rs
tests/generated/grid_display_none_fixed_size.rs
tests/generated/mod.rs

Fixes https://github.com/bevyengine/bevy/issues/7952
There is a silly bug in logic for selecting the layout algorithm that prioritised leaf layout over `display: none`. However, this wasn't noticed because that code path is only taken if the node in question:
- Does not have any children (because otherwise leaf layout doesn't apply)
- Is not itself a child node (because otherwise logic in the flexbox/grid layout modes makes it work anyway)

Fix `display: none` when it is set for the only node in the hierarchy

---

Cargo.toml
RELEASES.md

Release `0.3.4` version. Includes fix in #377

Prepare for 0.3.4 release

---

src/compute/flexbox.rs
tests/relayout.rs

Fix https://github.com/bevyengine/bevy/issues/7952 (Take 2)

Fix layout of direct flex children with `display:none` set

---

Cargo.toml
RELEASES.md

Changelog and version bump for `v0.3.5` release

Prepare for 0.3.5 release

---

Cargo.toml
RELEASES.md

Changelog and version bump for v0.3.6

Prepare for v0.3.6 release

---

src/compute/flexbox.rs

Reduces `tree.style()` calls in the flexbox implementation from 22 to 9. Idea was to improve perf, but it doesn't seem to have made much difference. It may make more difference for users of Taffy using alternative storage where style lookup is not just a Vec lookup though. And I think it's a minor improvement to code readability anyway, so worth merging.

Reduce style accesses

---

src/compute/flexbox.rs
test_fixtures/bevy_issue_8017.html
test_fixtures/bevy_issue_8017_reduced.html
tests/generated/bevy_issue_8017.rs
tests/generated/bevy_issue_8017_reduced.rs
tests/generated/mod.rs

Fixes https://github.com/DioxusLabs/taffy/issues/387
Fixes https://github.com/bevyengine/bevy/issues/8017
- https://drafts.csswg.org/css-sizing-3/#min-percentage-contribution
Above states that percentage sizes should not contribute to min-content sizes

Prevent percentages contributing to min-content sizes

---

.github/workflows/ci.yml
.github/workflows/dependencies.yml
Cargo.toml

- Speed up CI by using binary version of `cargo-deny` rather than compiling from source
- Move off unmaintained actions-rs actions

Upgrade to better Github Actions for faster and better maintained CI

---

test_fixtures/percentage_sizes_should_not_prevent_flex_shrinking.html
tests/generated/mod.rs
tests/generated/percentage_sizes_should_not_prevent_flex_shrinking.rs

The current test case works fine but is named after the bevy issue rather than the actual cause and contains unecesary styles. This adds an additional unit-style test.

Add fully reduced test case for #387

---

src/compute/flexbox.rs
src/compute/mod.rs
test_fixtures/bevy_issue_8082.html
test_fixtures/bevy_issue_8082_percent.html
tests/generated/bevy_issue_8082.rs
tests/generated/bevy_issue_8082_percent.rs
tests/generated/mod.rs
tests/generated/percentage_sizes_should_not_prevent_flex_shrinking.rs

Fixes bevyengine/bevy#8082 (wrapping nodes wrapping incorrectly).
The issue was incorrect constraints being passed to the child.

Fix wrapping nodes generating an incorrect min-content size

---

Cargo.toml
RELEASES.md

Update changelog and version number for `v0.3.8` release.

Prepare for 0.3.8 release

---

Cargo.toml
RELEASES.md

Release notes and version bump for `v0.3.10` release

Prepare for 0.3.10 release

---

src/style/grid.rs

(cherry picked from commit 55225737802b3e2a0e0ce6194c9fce2603a18a30)
Cherry picked from #414 but realized this was an unrelated change.
Clippy complains about duplicate imports, so cleaning that up.

Fix clippy lints

---

.github/workflows/ci.yml

Currently, we download and build taffy's dependencies on every CI run.
With this PR, we use [`cargo-cache`](https://github.com/Leafwing-Studios/cargo-cache) to cache the builds in order to speed up CI times.
`cargo-cache` is essentially just a wrapper around GitHub Action's `cache` action.
It automatically generates the `Cargo.toml` file for libraries to choose an appropriate cache key and then caches the target folder.
We have been using this with great success for [Emergence](https://github.com/Leafwing-Studios/Emergence).

Add caching to CI

---

src/compute/flexbox.rs
src/style/dimension.rs
test_fixtures/flex_grow_within_constrained_min_max_column.html
tests/generated/flex_grow_within_constrained_min_max_column.rs

Optimise performance of Flexbox layouts with min/max sizes.
I also fixed a test that I noticed had a missing semicolon which caused two of the styles to not be applied.
Currently the flexbox algorithm does a second pass of the entire layout algorithm (for that node) in the case that it has min- and max- sizes.
Currently we do not have benchmarks testing layouts with min/max sizes. Benchmarks results on the existing benchmarks are pretty neutral. **UPDATE**: I did a quick test locally by adding a min size to the setup code for our existing benchmarks, and this causes an exponential blowup on `main`. Fixed by this PR :)

Optimise flexbox layouts with min/max sizes

---

.github/workflows/ci.yml
Cargo.toml
RELEASES.md
src/compute/mod.rs
src/debug.rs
src/geometry.rs
src/prelude.rs
src/style/mod.rs

Fix #298 
- Does it make sense that Display::None is the default value for the node?

Moving flexbox behind a feature flag

---

RELEASES.md
src/prelude.rs

The prelude contained a single method that has been kept around for backwards compatibility. It is simply a wrapper around `FlexboxAlgorithm::perform_layout()`. The idiomatic way to use taffy now and going forward is to use the `perform_layout()` on the trait so I don't think we need to keep this around for much longer. 
The migration path is also very simple, but it is a breaking change.
Are there any reasons why we would not want this? Or want to delay this? I know #326 might change how end users interact with taffy, and so we might want to bundle these changes together?

Remove `layout_flexbox` function from prelude

---

src/compute/flexbox.rs
src/compute/grid/alignment.rs
src/compute/grid/mod.rs
src/compute/grid/track_sizing.rs
src/compute/grid/types/grid_item.rs
src/node.rs
src/tree.rs

The objective here it to make is easy to embed Taffy as part of a larger layout implementation rather than usage of Taffy requiring you to "buy in" to having all your layouting needs handled by Taffy.
This is the core change from #326
Fixes #28
See https://github.com/DioxusLabs/taffy/issues/28#issuecomment-1374941635
Seems to be relatively perf-neutral.

Trampoline child measurement/layout through the `LayoutTree` trait

---

RELEASES.md
src/compute/leaf.rs
src/compute/mod.rs
src/node.rs
src/tree.rs

The aim is again to simplify the `LayoutTree` trait by removing unncessary methods. In this case, it is achieved by making the generic `compute/mod` and `leaf` compute functions take `&mut Taffy` instead of `&mut impl LayoutTree`. This works because these methods are private, and are only used when using the built in `Taffy` tree anyway.
Split out from #326 
General PR review.

Remove `cache_mut`, `needs_measure` and `measure_node` methods from `LayoutTree` trait

---

src/compute/flexbox.rs
src/compute/grid/mod.rs
src/compute/mod.rs
src/lib.rs
src/tree.rs

We have a low-level API that we intend consumers of Taffy to use, but it's currently private!
Split out from https://github.com/DioxusLabs/taffy/pull/326
We may want to change the interface before releasing, but for now just making the existing interface public seems like a good start.

Make low-level layout algorithm functions public

---

src/style_helpers.rs

Fix a copy-paste error in a doc-comment

Fix TaffyAuto::AUTO docs

---

.github/workflows/ci.yml
src/compute/taffy_tree.rs

Currently CI fails due to missing feature flag
Does any have any idea how CI managed to pass in the PR itself?

Enable `taffy_tree` feature when running tests in CI

---

src/compute/mod.rs
src/compute/taffy_tree.rs
tests/relayout.rs

Fixes #452
As the `HiddenLayout` algorithm is now public and works with `&mut impl LayoutTree` trait, I had to create a second duplicate `perform_hidden_layout` function to also clear the cache of the `Taffy` struct
- Should we allow users to access the `HiddenLayout` algorithm?

Fix `display:none` caching issue

---

src/compute/mod.rs
tests/relayout.rs

Fix caching of `display:none` nodes (backport of #454 to 0.3.x)

---

.github/workflows/ci.yml

Speed up CI:
- Remove caching
- Split up the benchmarks into two jobs so that they can run in parallel
- Set opt-level=0 when compiling benchmarks (as we're not actually running them)
Somehow CI ended up with some jobs being cached and other not being. And I noticed that the UNcached jobs were running faster. Turns out that Taffy compiles fast enough and GHA's caching is slow enough that it's quicker not to cache!
With caching:
Without caching:

Remove caching from CI

---

Cargo.toml
src/util/math.rs
src/util/resolve.rs

Speed up CI
This is Taffy's dependency tree:
```bash
taffy v0.3.11
├── arrayvec v0.7.2
├── grid v0.9.0
│   └── no-std-compat v0.4.1
├── num-traits v0.2.15
│   [build-dependencies]
│   └── autocfg v1.1.0
└── slotmap v1.0.6
[build-dependencies]
└── version_check v0.9.4
```
This is `rstest`s dependency tree:
```bash
├── rstest v0.17.0
│   ├── futures v0.3.28
│   │   ├── futures-channel v0.3.28
│   │   │   ├── futures-core v0.3.28
│   │   │   └── futures-sink v0.3.28
│   │   ├── futures-core v0.3.28
│   │   ├── futures-executor v0.3.28
│   │   │   ├── futures-core v0.3.28
│   │   │   ├── futures-task v0.3.28
│   │   │   └── futures-util v0.3.28
│   │   │       ├── futures-channel v0.3.28 (*)
│   │   │       ├── futures-core v0.3.28
│   │   │       ├── futures-io v0.3.28
│   │   │       ├── …
```

Remove `rstest` dependency

---

src/tree/layout.rs
src/tree/mod.rs

Remove duplicate code. 
This is an accidental remnant of #448

Remove duplicate types definitions (`Layout`, `RunMode`, `SizingMode`, `SizeAndBaselines`)

---

Cargo.toml
src/compute/grid/explicit_grid.rs

- Upgrade `grid` dependency to `0.10`
- Also fixes a bug that prevented the `grid` feature being used in `alloc` (but no `std`) environments
This includes a nice change which removes grid's dependency on `no-std-compat`

Upgrade `grid` dependency to `0.10`

---

src/compute/grid/explicit_grid.rs
src/compute/grid/placement.rs
src/compute/grid/types/cell_occupancy.rs
test_fixtures/grid_auto_columns.html
test_fixtures/grid_auto_rows.html
tests/generated/grid_auto_columns.rs
tests/generated/grid_auto_rows.rs
tests/generated/mod.rs

Fix bugs in the CSS Grid track initialization and placement code
- Add tests for grid_auto_rows and grid_auto_columns
- Fix divide by zero when using grid_auto_rows/grid_auto_columns with zero negative implicit tracks
- Fix over-allocation / over counting of tracks in the CellOccupancyMatrix when auto-placing in grids that contain negative implicit tracks.
- Fix axis conflation in auto-placement code when grid_auto_flow is column
- Fix computation of auto track offset when initializing negative implicit tracks
While testing Taffy with [Blitz](https://github.com/DioxusLabs/blitz) I hit a panic caused by a divide-by-zero when attempting to use the grid_auto_rows property. Investigating this led me to realise that Taffy has no tests testing grid_auto_rows and grid_auto_columns. Adding some …

Fix CSS Grid "auto track" / placement bugs

---

RELEASES.md
src/tree/taffy_tree/tree.rs

Fixes #486
In the browser we have `insertBefore` method, however `insertBefore` have to handle a lot of case like move the node if it already in the document. I just want something simpler to control where to insert a new child node.

Add a new method `insert_child_at_index`.

---

RELEASES.md
src/compute/block.rs
src/compute/flexbox.rs
src/compute/grid/mod.rs
src/compute/taffy_tree.rs
src/tree/cache.rs
src/tree/layout.rs

I found minor misspelling. `RunMode::PeformLayout` changed into `RunMode::PerformLayout` (added missing `r`)

Minor misspelling fix (RunMode::PeformLayout -> RunMode::PerformLayout)

---

tests/caching.rs
tests/measure.rs
tests/root_constraints.rs

I found in a few manually-written tests (not generated) the next pattern for creating default `Style` - `Style::{ ..Default::default() }` (instead of `Style::default()`), that looks "unusual" (why here is 'create Style with all fields in default state', instead of simple 'create default Style' ?). This small minor PR fixes such places, to reduce mental load during reading :D

Minor: In a few tests simplified default Style construction

---

tests/border_and_padding.rs
tests/min_max_overrides.rs

I found it "unusual" that arguments "width" and "heights" in `tests`/{ `border_and_padding.rs`, `min_max_overrides.rs` } in reversed order. This small minor PR fixes it :)

Fixed unusual agrument order: [height, width] -> [width, height]

---

tests/border_and_padding.rs

During reading tests, I found "unusual", that in hand-written (not generated) test `tests/border_and_padding.rs` used [.ok()](https://doc.rust-lang.org/std/result/enum.Result.html#method.ok) instead of (commonly used in tests) [.unwrap()](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap).
`Taffy::compute_layout` returns `Result<(), TaffyError>`, so:
- calling `.ok()`  here simply produces `Option<()>`, discarding any errors;
- calling `.unwrap()` instead produces `()` value, but with **panic** in case of any `TaffyError`.
- Even if `compute_layout` currently [**not** poduces any errors](https://github.com/DioxusLabs/taffy/blob/d338f3731da519d182bbc074de46382984ab7c4a/src/compute/taffy_tree.rs#LL37C1-L62C2)
I think `.ok()` here is 'silent', …

Updated border_and_padding.rs - changed '.ok()' into '.unwrap()'

---

scripts/gentest/test_base_style.css

- Fix occasional weird rounding errors in gentests
- Align our gentest font with the Web Platform Test suite
The existing font we're using (and the weird line-height we need to get it to be exactly 10px high) leads to weird rounding errors which causes tests to incorrectly fail. The new Ahem font is the one used by the WPT. So this should also make it easier to port those tests in future.
The only slight downside here is that text in gentests will now look like a green square rather than an actual H character.

Switch gentests to use the Ahem font

---

src/tree/layout.rs
src/tree/taffy_tree/tree.rs

I found a discrepancy between documentation and code behavior. As I can see (after playing with `Style::padding`), `Layout`::`location` represents `top-left` point of the node rect, not `bottom-left`.
Also I added test for it. I don't know where to add it, so I added it into `src/tree/taffy_tree/tree.rs`

Minor: changed docs for Layout::location (bottom-left -> top-left) & added test

---

src/geometry.rs

Due to documentation changes in this PR https://github.com/DioxusLabs/taffy/pull/500, docs for `geometry::Point` must be changed too.

Minor: fixed comment for geometry::Point type

---

src/tree/taffy_tree/tree.rs

Fixes #510 
Seems that the parents list is not updated on the `remove` call, which I have to assume is a mistake.
See issue.

Remove "parent" references to a node when removing that node

---

src/compute/block.rs
src/compute/flexbox.rs
src/compute/grid/track_sizing.rs

I found, that `Clippy` pass in `GitHub CI` produces a few errors (about **mutable** reference usage without mutability) - this PR fixes them.

Fixed clippy lint errors (needless_pass_by_ref_mut)

---

src/compute/grid/types/cell_occupancy.rs

I found, that `CellOccupancyMatrix::is_area_in_range(...)` is immutable, but its not declared. For clarity in this PR removed `mut` near `self`.

Minor: `CellOccupancyMatrix::is_area_in_range()` now immutable

---

src/tree/taffy_tree/tree.rs

I found, that in `src/tree/taffy_tree/tree.rs` **everywhere** used `TaffyResult<T>`, except only one place - `Taffy::compute_layout(...) -> Result<(), TaffyError>`. This small minor PR fixes it :)

Minor: replaced `Result<(), TaffyError>` by `TaffyResult<()>` for consistency

---

src/compute/taffy_tree.rs
src/tree/cache.rs
src/tree/node.rs
src/tree/taffy_tree/tree.rs
tests/relayout.rs

- Fixes https://github.com/DioxusLabs/taffy/issues/501
- This fix is a bit hacky. I think ideally we'd want to differentiate between rounded and unrounded values in the public API. But the advantage of this implementation is that it's backwards compatible and can be released as a patch to the 0.3.x series. We can of course always improve upon this in the 0.4 release.
- It requires us to store both rounded and unrounded values, adding (I believe) 20 bytes per node. This is not ideal, but it seems like the simplest way to fix the issue. Perhaps in future we could improve upon this on future too.
General code review

Fix rounding accumulation bug

---

src/tree/taffy_tree/tree.rs

I apologize for not having time to make this changes to the last PR (https://github.com/DioxusLabs/taffy/pull/511), but I think, it will be great to add small descriptive-comment for newly added few lines of code and test-case from related issue (https://github.com/DioxusLabs/taffy/issues/510) - for anyone, who will read sources, not github issues history :)

Minor: added docs & test-case for updated 'Taffy::remove()' behaviour

---

src/compute/flexbox.rs

This is huge performance win on our 100k node "wide" benchmark, bringing the numbers roughly in line with our "deep" benchmarks for the same node count. Somewhat embarrassingly this one line was dominating performance for very wide trees:
```rust
let order = tree.children(node).position(|n| n == item.node).unwrap() as u32;
```
| Benchmark          | Node Count | Depth | Yoga ([ba27f9d]) | Taffy 0.3     | Taffy (main)  | Taffy (this PR) |
| ---                | ---        | ---   | ---              | ---           | ---           | ---             |
| yoga 'huge nested' | 1,000      | 3     | 408.72 µs        | 329.04 µs     | 177.16 µs     | 295.64 µs       |
| yoga 'huge nested' | 10,000     | 4     | 3.9276 ms        | 4.3486 ms     | 2.8241 ms     | 2.7671 ms       |
| yoga 'huge …

Flexbox: fix performance of nodes with very large numbers of children

---

.github/workflows/ci.yml
Cargo.toml

Make it easy for users to work out what version of Rust they need to compile Taffy.
Taffy will soon have C bindings, and that may well bring users who are less familiar with the Rust ecosystem and who may not be using the latest Rust version.
At most "latest stable" on a per-minor version basis, with the MSRV frozen for the life of that minor version at the minimum version that the `x.y.0` version actually compiles on (so no bumping in patch versions).
We currently support back to `1.65`.
Does this policy make sense?

Add rust-version to Cargo.toml (+ track in CI)

---

test_fixtures/flex/gap_column_gap_start_index.html
tests/generated/flex/gap_column_gap_start_index.rs
tests/generated/flex/mod.rs

Pulls in an extra test from https://github.com/facebook/yoga/pull/1408
We want to ensure our gentest suite continues to be a superset of Yoga's gentest suite

Add test for gap when the first child is position:absolute

---

RELEASES.md
src/compute/flexbox.rs
tests/caching.rs

Fixes bevyengine/bevy#9841
Pass cross-axis known_dimension when computing flex item min size
(fixes sizing of children that have inherent aspect ratio (e.g. images))

Pass cross-axis known_dimension when computing flex item min size (0.3.x)

---

RELEASES.md
src/compute/flexbox.rs

Fixes bevyengine/bevy#9841
Pass cross-axis known_dimension when computing flex item min size
(fixes sizing of children that have inherent aspect ratio (e.g. images))
I would like to add a gentest for this case. However, it requires extending the gentest harness to handle images, and I would like to avoid conflicts with https://github.com/DioxusLabs/taffy/pull/490 which also modifies that harness (and I suspect would be a pain to rebase on top of other changes). So I propose to create an issue (https://github.com/DioxusLabs/taffy/issues/546) for the test, merge just the fix, and then add the test once #490 lands.
I also intend to backport this to 0.3.x seeing as it's so small and it has been reported by a Bevy user. So I've stuck the changelog entry under 0.3.14.
Does this seem like a …

Pass cross-axis known_dimension when computing flex item min size

---

src/tree/cache.rs

Fixes a perf issue due to cache-thrashing that occurs with Flexbox columns.
Increased caches lots per node from 7 to 9, and updated slot-assingment algorithm to make use of those extra slots. specifically, MinContent and MaxContent/Definite sizes are now cached separately in both axis.
Found when investigating the following issues:
- #555 
- facebook/yoga#1409
- Optimise cache size by taking advantage of invariants encoded by the cache slot assignment algorithm. For example, slot 8 is only used if `known_dimensions` are `(None, None)` and `available_space` is `(MinContent, MinContent)`. So storing the value of those inputs as cache keys is unnecessary for that slot.
- Improve benchmarks. It has become apparent that there are a lot of cases our current benchmarks don't cover: columns, …

Fix caching for flexbox columns

---

RELEASES.md

Sync release notes from `0.3.x` branch to `main` following the `0.3.16` release.

Update release notes for 0.3.16 release

---

RELEASES.md
src/compute/block.rs
src/compute/flexbox.rs
src/compute/grid/mod.rs
src/compute/leaf.rs
src/compute/mod.rs
src/compute/taffy_tree.rs
src/lib.rs
src/style/mod.rs
src/tree/cache.rs
src/tree/layout.rs
src/tree/mod.rs
src/tree/taffy_tree/tree.rs

Simplify code. Particularly the "generic algorithm" code.
- Remove `LayoutAlgorithm` trait and switch to plain functions
- Rename `SizeBaselinesAndMargins` to `LayoutOutput` (name was getting ridiculously long)
- Create `LayoutInput` struct to hold input parameters.
- Implement `std::fmt::Display` for `taffy::style::Display` (used for debug logging)
Public API for algorithm compute functions is now:
- `compute_flexbox_layout`
- `compute_grid_layout`
- `compute_leaf_layout`
- `compute_hidden_layout`
- `compute_node_layout`
All plain functions exported from the root.
- https://github.com/DioxusLabs/taffy/issues/559
- The `LayoutAlgorithm` trait never worked very well, with the `leaf` mode in particular not able to conform to it. I expect this to get worse in future as I have plans to …

Remove `LayoutAlgorithm` trait

---

src/compute/flexbox.rs

This import is unnecessary and shouldn't be there.

Remove `core::f32` import from flexbox.rs

---

benches/Cargo.toml
benches/benches/flexbox.rs
benches/src/lib.rs
benches/src/taffy_03_helpers.rs
benches/src/taffy_helpers.rs
benches/src/yoga_helpers.rs

Allow us to determine how performance has changed since the last major Taffy version.
- Depend on Taffy 0.3 (as well as current Taffy) in the benchmarks create
- Implement `BuildTree` trait for Taffy 0.3
- Add a `taffy03` feature flag which runs benchmarks against Taffy 0.3
- Simplify benchmarking code with macros
Since we refactored the benchmarks in https://github.com/DioxusLabs/taffy/pull/472, simply checking out the old branch no longer gives a useful comparison.

Add comparative benchmarks with Taffy 0.3

---

src/compute/flexbox.rs
src/compute/grid/types/grid_item.rs
src/geometry.rs
src/style/flex.rs
src/tree/layout.rs
src/tree/mod.rs

This enables Taffy to be integrated with Xilem.
See: https://github.com/linebender/xilem/pull/140
- Add `RequestedAxis` enum
- Add `axis: RequestedAxis` parameter to child measurement and plumb through to various places
- API design review
- Should we split apart the `compute_child_layout` methods on the `PartialLayoutTree` trait? Because the `axis` parameter is only really relevant to the "measure child" case rather than "perform layout" case. Also, the "measure child" case could return `f32` instead of `LayoutOutput` in that case. Which would also reduce cache size.

Pass axis information when measuring a child's size

---

src/tree/cache.rs
tests/caching.rs

This gives a nice performance boost (~10-20%) on "deep" benchmarks, and also reduces memory usage.

Specialize cache by `RunMode`

---

src/compute/flexbox.rs
src/lib.rs
src/style/mod.rs
src/tree/layout.rs
src/tree/taffy_tree.rs

Make it easier to get started with Taffy by providing a high-level introduction to the API
Any feedback on the content of the documentation itself is welcome

Improve main module (lib.rs) docs + re-export more types at the crate root

---

src/tree/node.rs
src/tree/taffy_tree.rs

Fix a couple of issues that came when I tried to update Bevy to Taffy `main`.
- Derive `Hash` for `NodeId`. Bevy uses `NodeId` as a `HashMap` key which doesn't work without a `Hash` impl.
- Add a `get_node_context` method. We previously only have `get_node_context_mut` method, but Bevy needs to be able to check whether a node has context without having mutable access to the tree.
None. These changes are uncontroversial.

Bevy compatibility tweaks

---

examples/custom_layout_tree_owned.rs
examples/custom_layout_tree_vec.rs
src/compute/block.rs
src/compute/flexbox.rs
src/compute/grid/alignment.rs
src/compute/grid/mod.rs
src/compute/grid/types/grid_item.rs
src/compute/mod.rs
src/tree/mod.rs
src/tree/taffy_tree.rs

This makes it easier to integrate with Taffy as:
- It means you don't necessarily have to store the layout as a `taffy::Layout` struct
- It allows you to run logic just after the layout is set
It also makes it clear that Taffy's algorithms do not read from the layout (and removes the one case where they did!).
This change is motivated by the Xilem integration https://github.com/linebender/xilem/pull/140

Convert mutable layout getters to layout setters

---

src/compute/mod.rs
src/tree/mod.rs
src/tree/node.rs
src/tree/taffy_tree.rs

Better code organisation. This struct is only used in the taffy_tree module, and can be made private if it also defined within this module.

Move `NodeData` struct into `taffy_tree` module

---

Cargo.toml
examples/cosmic_text.rs

- Fixes #216
- Gives a realistic example of integrating text layout with Taffy

Add cosmic-text example

---

examples/custom_tree_owned.rs
examples/custom_tree_owned_partial.rs
examples/custom_tree_owned_unsafe.rs
examples/custom_tree_vec.rs
src/compute/block.rs
src/compute/flexbox.rs
src/compute/grid/alignment.rs
src/compute/grid/mod.rs
src/compute/grid/track_sizing.rs
src/compute/grid/types/grid_item.rs
src/compute/mod.rs
src/lib.rs
src/prelude.rs
src/tree/mod.rs
src/tree/taffy_tree.rs
src/tree/traits.rs
src/util/debug.rs
src/util/mod.rs
src/util/print.rs

- Fixes https://github.com/DioxusLabs/taffy/issues/569
With the existing trait setup the `print_tree` function requires `&mut self` which is silly.
- Does this trait structure seem reasonable.

Split tree traits

---

Cargo.toml
RELEASES.md

Feature `serde` of `taffy` was rigidly set to depend on the `serde` crate with its default features (ie: `std`) enabled- this meant that despite disabling the `std` feature in `taffy` it still would not compile for `no_std` targets when the `serde` feature was enabled.
This was a straightforward fix, simply opting out of `serde` default features and selectively re-enabling them alongside the corresponding `taffy` features.
See here for a quick reference affirming Serde `no_std` compatibility: https://serde.rs/no-std.html

Make `serde` dependency compatible with `no_std` environments

---

Cargo.toml
RELEASES.md
src/tree/taffy_tree.rs

As in #592, the `slotmap` dependency- used via the `taffy_tree` feature- wasn't reflecting the status of the `std` feature of `taffy`; this PR applies the same changes to the `slotmap` dependency and `std` feature.
This PR also requires switching the backer for `TaffyTree`'s node context data from [`slotmap::SparseSecondaryMap`](https://docs.rs/slotmap/latest/slotmap/struct.SparseSecondaryMap.html) to [`slotmap::SecondaryMap`](https://docs.rs/slotmap/latest/slotmap/struct.SecondaryMap.html) in `no_std` contexts.
Per the `slotmap` docs, they are perfectly compatible with each other outside of potential performance differences in certain cases- however, I would say that the possibility of being a bit slower in `no_std` contexts is better than not being able to compile at all.
#592, …

Make `slotmap` dependency compatible with `no_std` environments

---

RELEASES.md
src/tree/taffy_tree.rs

Useful method when dealing with mutable borrows between a parent and child node at the same time.

add get_disjoint_node_context_mut to tree

---

examples/custom_tree_owned_partial.rs
examples/custom_tree_owned_unsafe.rs
examples/custom_tree_vec.rs
src/compute/leaf.rs
src/tree/taffy_tree.rs
tests/measure.rs

Allow use of measure functions in cases where extra context information is not required.
- Fixes #597
I believe this is a strict generalisation of functionality. If users want to return a zero size for cases where context is `None` they can do this within their measure function (and as `node_context` was already an `Option<T>` they would have to have done this anyway with the existing API).

Call measure function on leaf nodes even if the node does not have context

---

tests/generated/flex/align_flex_start_with_stretching_children.rs

Ensure generated code is up to date with source files.
Generation was not done as part of #611 
CC: @waywardmonkeys. To ensure this doesn't happen in future, you need to run `cargo gentest` to regenerate the tests after following the setup instructions in CONTRIBUTING.md. We should also add a CI check for this, but it's non-trivial as it involves running Chrome/Chromium in CI.

Regenerate tests

---

Cargo.toml
examples/cosmic_text.rs

Keep example up to date with latest library version.
Dependabot notified us of this (https://github.com/DioxusLabs/taffy/pull/614) but a small code change was also required.

Upgrade cosmic_text example to cosmic-text 0.11.2

---

src/tree/taffy_tree.rs

The `parent` method is a useful method when interacting with the tree
This method was correctly removed from the `LayoutTree` trait, but that left the `TaffyTree` struct with no such method at all. This PR adds it back as an inherent method on `TaffyTree`.

Add parent method to the TaffyTree

---

Cargo.toml
RELEASES.md

Update version number and release notes in preparation for a `v0.4.0` release of Taffy.

Prepare for v0.4.0 release

---

README.md

Better document:
- Projects using Taffy (fixes #588)
- Available bindings for Taffy

Add more users and bindings to README

---

examples/common/text.rs

Fixes an off-by-one error in the wordwrap calculation
Fixes: #628
#628
Equivalent screenshot of bug in #628 showing that this is fixed:

fix: wordwrap calculation in measure example

---

.github/workflows/ci.yml
src/compute/grid/mod.rs
src/compute/mod.rs
src/util/debug.rs

Compilation with the `debug` feature was broken. This fixes and adds a CI check to prevent future regressions.

Fix debug mode

---

src/compute/grid/track_sizing.rs
test_fixtures/grid/grid_taffy_issue_624.html
tests/generated/grid/grid_taffy_issue_624.rs
tests/generated/grid/mod.rs

Fixes #624
This is correctness fix for content-sizing grid tracks. It turns out that we weren't respecting growth limits when distributing  space to base sizes. I suspect that this was disabled at some point to fix another bug as the code contains a limit function which was previously set to Infinity. But simply setting the growth limit as the limit function appears to pass all existing tests while fixing this bug.
https://github.com/w3c/csswg-drafts/issues/10095

Grid: Respect growth limits when distributing space to base sizes

---

src/compute/grid/track_sizing.rs

Reduce binary size caused by Taffy. This roughly halves Taffy's binary footprint (from ~300kb to ~150kb). Benchmark results are neutral (seem unchanged).
Analysis done with `cargo bloat --example basic --release -n 150 | grep taffy`. Note how we were previously generating 4 copies of the `resolve_intrinsic_track_sizes` function.
**Before:**
```
7.7%   9.9%  54.0KiB     taffy taffy::compute::grid::track_sizing::resolve_intrinsic_track_sizes
7.7%   9.8%  53.9KiB     taffy taffy::compute::grid::track_sizing::resolve_intrinsic_track_sizes
7.7%   9.8%  53.9KiB     taffy taffy::compute::grid::track_sizing::resolve_intrinsic_track_sizes
7.7%   9.8%  53.7KiB     taffy taffy::compute::grid::track_sizing::resolve_intrinsic_track_sizes
4.6%   5.9%  32.6KiB     taffy …
```

Deduplicate `track_sizing_algorithm` function

---

Cargo.toml
RELEASES.md

Release recent alignment and binary size fixes prior to landing https://github.com/DioxusLabs/taffy/pull/635 which will be breaking.

Prepare for v0.4.2 release

---

src/style_helpers.rs

flex's argument needs to be Into f32, a plain float literal is f64 which does not work, I just specified that the argument here is f32
fixes #642

evenly_sized_tracks - fix simple compile error

---

Cargo.toml
RELEASES.md

Ensure Taffy 0.3.x compiles on recent nightly versions of rustc
- #642
- #643

Prepare for v0.3.19 release

---

Cargo.toml
RELEASES.md

Ensure Taffy compiles on recent nightly versions of rustc
- #642
- #643
- https://github.com/rust-lang/rust/issues/123831

Prepare for v0.4.3 release

---

RELEASES.md
src/compute/common/alignment.rs
src/compute/flexbox.rs
src/compute/grid/alignment.rs
tests/generated/flex/align_content_space_around_wrapped_negative_space.rs
tests/generated/flex/align_content_space_around_wrapped_negative_space_gap.rs
tests/generated/flex/align_content_space_evenly_wrapped_negative_space.rs
tests/generated/flex/align_content_space_evenly_wrapped_negative_space_gap.rs
tests/generated/flex/bevy_issue_10343_block.rs
tests/generated/flex/bevy_issue_10343_flex.rs
tests/generated/flex/bevy_issue_10343_grid.rs
tests/generated/flex/justify_content_column_space_around_negative_space.rs
tests/generated/flex/justify_content_column_space_around_negative_space_gap.rs
tests/generated/flex/justify_content_column_space_evenly_negative_space.rs
tests/generated/flex/justify_content_column_space_evenly_negative_space_gap.rs
tests/generated/grid/grid_align_content_space_around_negative_space_gap.rs
tests/generated/grid/grid_justify_content_space_around_negative_space_gap.rs
tests/generated/grid/grid_justify_content_space_evenly_negative_space_gap.rs

The spec for fallback content alignment (in the case that the content overflows it's container) has changed. Rather than laying out content at a negative offset where it cannot be viewed it now falls back to safe start alignment. This PR is designed to update Taffy to match the new spec.
- Spec issue https://github.com/w3c/csswg-drafts/issues/10154 (note: this issue is for a *further* update/tweak compared to the change that this issue was originally opened for. `space-around`/`space-evenly` now fallback to `safe flex-start` rather than `flex-start`)
- Yoga fix https://github.com/facebook/yoga/commit/6f10656868c2eca9b2eae55ad754e01e70565f69
- WPT test https://github.com/web-platform-tests/wpt/blob/master/css/css-flexbox/align-content-wrap-003.html

Fixes for content alignment spec updates

---

RELEASES.md
src/compute/flexbox.rs
test_fixtures/flex/padding_border_overrides_size_root.html
tests/generated/flex/mod.rs
tests/generated/flex/padding_border_overrides_size_root.rs
tests/root_constraints.rs

- Fixes https://github.com/DioxusLabs/taffy/pull/651
- This bug only seems to affect nodes that happen to be the root of the tree.
- Test moved to `tests/root_constraints`
- Fix changed so that override does not apply to `known_dimensions`
- A generated test covering this case added
- Removed import of `Add` trait (uses `+` syntax rather than calling `.add` so it isn't needed)

Ensure that root flexbox node sizes are floored by their padding border

---

RELEASES.md
src/compute/grid/types/grid_item.rs
test_fixtures/grid/chrome_issue_325928327.html
tests/generated/grid/chrome_issue_325928327.rs
tests/generated/grid/mod.rs

Fix an issue surfaced by the linked test in https://github.com/DioxusLabs/taffy/issues/653.
Specifically a grid area may have a defined size even when the available space for the grid does not (for example if the grid container has fixed pixel sizing).

Use grid area size not available space when applying aspect ratio to grid containers

---

src/compute/block.rs
test_fixtures/block/block_item_max_width.html
test_fixtures/block/block_item_min_width_overrides_max_width.html
tests/generated/block/block_item_max_width.rs
tests/generated/block/block_item_min_width_overrides_max_width.rs
tests/generated/block/mod.rs

Fix min and max width for block items (items of block layouts)

Clamp block item stretch widths by their min and max width

---

src/compute/block.rs
test_fixtures/block/block_margin_auto_left_and_right_with_auto_width.html
tests/generated/block/block_margin_auto_left_and_right_with_auto_width.rs
tests/generated/block/mod.rs

- Fix auto margin computation in block layout
Taffy was previously special casing the case where all of the width, left, and right properties are auto, but browsers do not seem to do this (and this breaks auto margin centering with default values of left and right)

Fix auto margin computation in block layout

---

src/style/grid.rs

Fixes a panic. Nobody should be specifying grid line zero because it's invalid, but as it *can* be specified it definitely shouldn't panic. We already had logic to fall back to "auto" when "0" is specified but there was a fault in that logic.
We could make GridLine take `NonZeroi16`.

Fix panic when GridLine 0 is specified

---

src/compute/flexbox.rs
src/compute/mod.rs
test_fixtures/flex/blitz_issue_88.html
tests/generated/flex/blitz_issue_88.rs
tests/generated/flex/mod.rs

Fix computation of intrinsic main size when it depends on a child's known cross size

---

.github/workflows/ci.yml
Cargo.toml
src/lib.rs

I noticed that the feature flags were not documented and added these
changes so the library documentation is kept perpetually updated.
- Use [document-features](https://crates.io/crates/document-features)
crate to automatically add documentation about the features to the
crate documentation at the crate level.
- Use the doc_auto_cfg feature to automatically add documentation
to every item that requires a feature flag to be enabled. This is
behind a docsrs feature flag as it can only be enabled using the
nightly toolchain and this allows the documentation to be built with
the stable toolchain when the feature is not enabled. See
<https://doc.rust-lang.org/rustdoc/unstable-features.html#doc_auto_cfg-automatically-generate-doccfg>
for more information.
- …

Document feature flags and scrape examples

---

src/compute/block.rs
src/compute/mod.rs

- Fix block nodes stretch-fitting when they shouldn't.
- Block nodes were (unconditionally) stretch-fitting themselves. However block nodes only stretch-fit into available space if their parent is also a block node (it is really block containers that cause stretch-fitting, not block children).
- Block nodes no longer stretch-fit into available space
- The root node (regardless of display mode) now *does* stretch-fit into available space (if it is definite). I think this is correct, but not 100% sure.
- Block nodes still unconditionally stretch-fit their children. This is usually what we want, but there are exceptions in HTML (for example table children of blocks do not stretch-fit) which we will likely want to support in future.
Does the root node being forced into taking up all available …

Block stretch sizing fixes

---

Cargo.toml
RELEASES.md

Update version number and release notes for v0.5.2 release

Prepare from v0.5.2 release

---

Cargo.toml

This is required for the crate to build/publish correctly with the new "scrape examples" documentation feature.

Include examples in Cargo.toml package

---

src/compute/block.rs
src/compute/flexbox.rs
src/compute/grid/alignment.rs
src/compute/mod.rs
src/tree/layout.rs

It is useful for users of Taffy to be able to determine the sizes the computed margin for each node. This is especially the case when auto margins are specified and margin cannot easily be determined just from the styles.
Padding and border are already output in the `Layout`.

Output computed margins in `Layout`

---

src/tree/taffy_tree.rs

Fixes `.print_tree()` method when rounding is disabled. In the original version, if rounding is disabled, `.print_tree()` just prints zeros.
Original version if rounding is enabled prints:
```
TREE
└──  FLEX COL [x: 0    y: 0    w: 800  h: 600  content_w: 600  content_h: 300  border: l:0 r:0 t:0 b:0, padding: l:0 r:0 t:0 b:0] (NodeId(4294967299))
└──  GRID [x: 0    y: 0    w: 600  h: 300  content_w: 300  content_h: 300  border: l:0 r:0 t:0 b:0, padding: l:0 r:0 t:0 b:0] (NodeId(4294967298))
└──  LEAF [x: 100  y: 150  w: 200  h: 150  content_w: 0    content_h: 0    border: l:0 r:0 t:0 b:0, padding: l:0 r:0 t:0 b:0] (NodeId(4294967297))
```
Original version if rounding is disabled prints:
```
TREE
└──  FLEX COL [x: 0    y: 0    w: 0    h: 0    content_w: 0    content_h: 0    border: l:0 r:0 …
```

Fixed print_tree() when rounding is disabled

---

src/compute/block.rs
src/compute/flexbox.rs
src/compute/grid/mod.rs
test_fixtures/block/block_absolute_resolved_insets.html
test_fixtures/flex/absolute_resolved_insets.html
test_fixtures/grid/grid_absolute_resolved_insets.html
tests/generated/block/block_absolute_resolved_insets.rs
tests/generated/block/mod.rs
tests/generated/flex/absolute_resolved_insets.rs
tests/generated/flex/mod.rs
tests/generated/grid/grid_absolute_resolved_insets.rs
tests/generated/grid/mod.rs

Currently, absolute insets seem to be resolved incorrectly
Right now both relative and absolute insets are resolved against the container size.
The common (and probably specified) behavior is to resolve them against `container_size - border `, and in taffy's case, I'd assume `container_size - border - scrollbar_width` when applicable
Note: Parent's padding does not seem to affect insets
https://codepen.io/juliascript/pen/abrJvZa
https://www.yogalayout.dev/playground?code=DwGQhgng9grgLgAgMZQHYDMCWBzAvAb3xgGcBTAdVICMARU9MGAGzmIC4E4AnGUgXz4A+AFAIEwAHJQAJqQTE4EJqQL4A7pmlwAFhwCMABgMAaBNtI5tcfUdMAHMNOmZU2G6apQusruU079AFYEARExMUkZOQUlFUJRcLE7KGJMOEw0DgByMCpiKCZ4UizjBMS4KDtswIMAUhKy8OV0awQswzqGxLENLV0EAGYTRrFzS1ah0sSBBAB6MPFZqVkRYFnwaHhBIA
```
TREE
└──  FLEX ROW [x: 0    y: 0    w: 100  h: 100 …
```

Absolute Insets should be resolved against the container size minus border

---

test_fixtures/flex/align_items_center_with_max_height_with_padding_border.html
tests/generated/flex/align_items_center_with_max_height_with_padding_border.rs

This a flexbox test, however it is unnecessarily relying on block layout. Update it to only use flexbox.

Don't use block layout in flexbox test

---

src/tree/layout.rs

Useful for using as `..LayoutOutput::DEFAULT`.

Add `DEFAULT` constant to LayoutOutput

---

src/tree/cache.rs

Make it easier to embed `Cache` inside types that implement `Debug` and/or `Clone`.

Impl debug, clone for Cache

---

examples/custom_tree_owned_partial.rs
examples/custom_tree_owned_unsafe.rs
examples/custom_tree_vec.rs
src/compute/block.rs
src/compute/flexbox.rs
src/compute/grid/alignment.rs
src/compute/grid/explicit_grid.rs
src/compute/grid/implicit_grid.rs
src/compute/grid/mod.rs
src/compute/grid/placement.rs
src/compute/grid/types/grid_item.rs
src/compute/leaf.rs
src/compute/mod.rs
src/style/flex.rs
src/style/grid.rs
src/style/mod.rs
src/tree/mod.rs
src/tree/taffy_tree.rs
src/tree/traits.rs

Allow users of Taffy to bring their own style representation(s).
While we have support for custom node tree representations, we currently enforce usage of a concrete style representation. Additionally, that style representation is shared across all algorithms and thus must include the styles for Flexbox, CSS Grid and Block layout, making it quite large. A problem which will only get worse if non-css algorithms are supported in future.
- Feedback on the trait hierarchy design

"Traitify" the `Style` struct

---

src/compute/flexbox.rs
test_fixtures/flex/flex_grow_0_min_size.html
tests/generated/flex/flex_grow_0_min_size.rs
tests/generated/flex/mod.rs

This is a correctness fix for the flexbox algorithm. It ensures that the automatic minimum size still applies even when the flex-basis is explicitly set to 0 and no flex growing is permitted.

Flexbox: Fix flooring hypothetical_main_size by computed min size

---

src/compute/grid/explicit_grid.rs
src/compute/grid/placement.rs
src/compute/grid/track_sizing.rs

This fixes 3 crashes/panics in the css grid algorithm.

Fix panics in the grid algorithm

---

src/compute/flexbox.rs
test_fixtures/flex/multiline_column_max_height.html
tests/generated/flex/mod.rs
tests/generated/flex/multiline_column_max_height.rs

Fix flexbox wrapping when a max main size style is present
This is a fix for the WPT test `css/css-flexbox/multiline-column-max-height.html`

Fix flexbox wrapping when a max main size style is present

---

src/compute/block.rs
src/compute/leaf.rs

Fix case where Taffy allowed margins to collapse through an element when it shouldn't have
Fixes horizontal separator div on servo.org in blitz

Fix case where Taffy allowed margins to collapse through an element when it shouldn't have

---

src/tree/cache.rs
src/tree/layout.rs
src/tree/taffy_tree.rs

This makes it possible to store a TaffyTree in a struct that derives
the Debug and Clone traits
I wanted to create a struct that stored a TaffyTree, but was unable to as the struct derived Debug and Clone.
Rather than switch to a manual implementation, it makes sense to derive Debug in Taffy.
Additionally several types were missing PartialEq implementations.

feat: derive Debug and PartialEq for tree types

---

src/style/mod.rs

There was a typo in the trait impl causing it to be implemented for `&Style` rather than `Style`.

Implement FlexContainerStyle for Style as well as &Style

---

src/compute/block.rs
src/style/block.rs
src/style/mod.rs
src/tree/traits.rs

Table children of block nodes are treated specially: they don't get stretch-sized in the inline axis. This PR allows us to implement that behaviour.

Add `item_is_table` for block items

---

deny.toml

Many "deny" settings have been removed because they are now the default.
See: https://github.com/EmbarkStudios/cargo-deny/pull/611
Fix CI

Upgrade deny.toml to version 2

---

src/style/alignment.rs
src/style/grid.rs
src/tree/traits.rs

Ensure that Taffy passes the latest clippy.

Fix `clippy::too_long_first_doc_paragraph` lint

---

Cargo.toml
RELEASES.md

Update changelog and version number for 0.6.0 release

Prepare for 0.6.0 release

---

RELEASES.md
src/compute/grid/explicit_grid.rs
test_fixtures/grid/grid_auto_fit_definite_percentage.html
test_fixtures/grid/taffy_issue_721.html
tests/generated/grid/mod.rs
tests/generated/grid/taffy_issue_721.rs

- Fixes #721
Previously, when computing the repetition count for auto repetitions, Taffy was only checking whether the container had a fixed pixel size or max-size. Taffy now correctly also checks for a percentage which resolves against a definite size.

Fix calculation of `auto-fill`/`auto-fit` repetition count when container has a definite percentage size

---

src/compute/flexbox.rs
test_fixtures/grid/grid_taffy_issue_591.html
tests/generated/grid/grid_taffy_issue_591.rs
tests/generated/grid/mod.rs

- Fixes #591 
`min-size` styles of flexbox items ought to be taken into account when determining the intrinsic size of Flexbox containers.

Fix intrinsic sizing min size

---

scripts/gentest/src/main.rs

Fix clippy lints properly rather than ignoring. In one case the ignore was to work around a clippy bug which has now been fixed.

Remove clippy lint ignores

---

src/lib.rs

The `custom_tree_owned_partial description` was the same as the unsafe example. 
Updated it to reflect my understanding of how NodeIds are used to get hold of Nodes in the example

fix copy paste error about low-level example description

---

examples/custom_tree_owned_partial.rs
src/tree/traits.rs

Missed to update the documentation in `traits.rs` in #730 
For my own understanding and for others clarification, I also added the reason why this example is limited to `TraversePartialTree` - Hopefully it's correctly described!

fix description in traits.rs

---

examples/custom_tree_owned_partial.rs
examples/custom_tree_owned_unsafe.rs
examples/custom_tree_vec.rs
src/style/mod.rs
src/tree/taffy_tree.rs
taffy_stylo/src/arc.rs
taffy_stylo/src/borrowed.rs

Reduce incidental diff from incoming PRs using nightly rustfmt (stable rust currently doesn't format these sections of code at all, so there is no conflict).
I don't really like this formatting (seems very verbose), but it's not going to be practical to use formatting other than what rustfmt produces, and there doesn't seem to be a config option for this atm.

Apply latest (nightly) rustfmt (format associated types with GATs)

---

.cargo/config.toml
justfile

This means that we don't have to have `.cargo/config` committed, which allows people to use that file to customize their build without conflicts.

Move cargo config aliases to justfile.

---

src/compute/block.rs

- Improve the correctness of the block implementation
Discovered through Blitz's new WPT test runner

Block: ignore margin collapsing when computing static position of abspos items

---

.github/workflows/ci.yml
Cargo.toml
examples/cosmic_text/Cargo.toml
examples/cosmic_text/src/image.rs
examples/cosmic_text/src/main.rs

Save taffy developers from compiling cosmic-text every time they run tests. Also speeds up test jobs in CI.

Move cosmic-text example into it's own crate

---

deny.toml

Ensure that duplicates dependencies are detected again in future.

Remove duplicate detection skips from `deny.toml`

---

src/tree/layout.rs

Make it easier for users wanting to access the content box layout of a Node.
Servo's layout system is content-box centric. These methods reduce the boilerplate required in the Servo integration.

Add content-box helper methods to Layout

---

examples/custom_tree_owned_partial.rs
examples/custom_tree_owned_unsafe.rs
examples/custom_tree_vec.rs
src/compute/mod.rs
src/tree/taffy_tree.rs
src/tree/traits.rs

- Allow Taffy to be used without caching
- Makes it easier to use custom cache representations

Split out caching into separate `CacheTree` trait

---

src/compute/block.rs

Fixes  ~40 WPT tests css-flexbox and ~70 in css-grid that incidentally rely on this feature (because they use absolute positioning to position one div under another)

Improve interaction of abspos children of block containers with margin collapsing

---

src/style/dimension.rs

Improve documentation of the API in an area where there has been confusion in the past
- #625

Document that Taffy percentages are represented by the range [0, 1] not [0, 100]

---

src/tree/taffy_tree.rs

It doesn't seem like you can directly access the unrounded node layout, you need to do something annoying like:
```rust
self.taffy.disable_rounding();
let unrounded_layout = self.taffy.layout(*taffy_node).unwrap();
self.taffy.enable_rounding();
```
This PR adds a helper method `unrounded_layout` to `TaffyTree`  that returns a reference to the unrounded node layout values so that you can get them without toggling the rounding state for the whole tree each time.

`unrounded_layout` helper method

---

.github/workflows/ci.yml
Cargo.toml
src/compute/grid/mod.rs
src/compute/mod.rs
src/lib.rs
src/tree/layout.rs
src/tree/mod.rs
src/tree/taffy_tree.rs
src/tree/traits.rs

Expose computed grid layout information, which includes `grid-template` and `grid-placement`.
This changes attempts to add `LayoutPartialTree`'s API to store and get the layout information in `TaffyTree` with low level API in mind. 
Discussion about whether the structure and information of grid layout is desirable and correct is appreciated. 
Kindly provide general review of code structure, regarding the compliance with Rust and Taffy code recommendation.

Add API to expose computed grid information

---

CHANGELOG.md
Cargo.toml

Update changelog and version number for `v0.7.2` release.

Prepare for v0.7.2 release

---

README.md

Keep the "users of taffy" list in the README up to date.
- Servo now uses Taffy for CSS Grid

Add Servo as a user of Taffy. List Blitz instead of Dioxus

---

src/tree/taffy_tree.rs

- Fixes #778
- Don't require`&mut` where it's not actually necessary

Use &self instead of &mut self for detailed_layout_info method

---

examples/custom_tree_owned_partial.rs
examples/custom_tree_owned_unsafe.rs
examples/custom_tree_vec.rs
src/compute/block.rs
src/compute/flexbox.rs
src/compute/grid/alignment.rs
src/compute/grid/explicit_grid.rs
src/compute/grid/mod.rs
src/compute/grid/track_sizing.rs
src/compute/grid/types/grid_item.rs
src/compute/leaf.rs
src/compute/mod.rs
src/lib.rs
src/style/dimension.rs
src/style/grid.rs
src/tree/taffy_tree.rs
src/tree/traits.rs
src/util/resolve.rs

`calc()` is super-useful for creating advanced layouts. This PR implements `calc()` in the low-level API. Notably this excludes the actual evaluation of `calc()` expressions. Blitz and Servo can both use [Stylo](https://github.com/servo/stylo) for this.
A built-in implementation of `calc()` expressions in Taffy is considered desirable, but is left as a follow-up.
- Part of #225 
- Depends on https://github.com/DioxusLabs/taffy/pull/769
The performance impact discussed in https://github.com/DioxusLabs/taffy/pull/769 also applies to this PR, but there appears to be no additional performance impact compared with https://github.com/DioxusLabs/taffy/pull/769.
- General code review

Implement `calc()` in the low-level API

---

.github/workflows/ci.yml
Cargo.toml
src/style/dimension.rs

- Reinstate lower MSRV of Rust 1.65
- We want `const` constructors for values.
- We were using `f32::to_bits` and `f32::from_bits` for this functionality since #769
- These functions were only stabilised in Rust 1.83
- This PR inlines those functions into Taffy which allows us to reduce MSRV back to 1.65 at the cost of two lines of unsafe code.

Reinstate 1.65 MSRV

---

src/compute/grid/mod.rs

Expose `DetailedGridInfo` information for grid with empty items.
Move the operation to set the detailed info, allowing empty grid element to have it exposed.

Expose grid info for empty grid

---

src/compute/grid/types/grid_item.rs
src/style/mod.rs

Replaced items such as images and form controls are special cased in cases. This change represents that in Taffy.
This is necessary to pass tests cases in the following WPT tests:
- `css/css-grid/grid-items/grid-minimum-size-grid-items-021.html`
- `css/css-grid/grid-items/percentage-size-indefinite-replaced.html`

Special-case "compressible replaced elements" in grid sizing algorithm

---

src/compute/grid/types/grid_item.rs
src/style/mod.rs

This reverts commit 9660b2cf8884879037f88415db6be8168a9aaa49.
Make it easier to land changes in Servo independently.
The change being reverted here is correct. However there are some cleanups to earlier `calc()` work that I want to land first.

Revert "Special-case "compressible replaced elements" in grid sizing algorithm (#785)"

---

src/style/dimension.rs
src/style/grid.rs

Make it easier to construct style dimension values:
- Inherent methods make it possible to call the constructor without importing a trait
- Inherent methods can be `const`. Making it possible to safely construct dimension values in a `const` context
- Having constructors for `calc` allows `calc()` values to be constructed safely.

Style value constructors

---

src/compute/grid/track_sizing.rs

Fix infinite loop.
Both HN and Reddit were hanging in Blitz before this fix.

Fix infinite loop due to float precision in grid layout maximise tracks step

---

src/style/compact_length.rs

Ensure taffy `main` continues to pass clippy linting. This lint suggests that we use the newly stabilised `f32::to_bits` and `f32::from_bits` functions. But we are explicitly avoiding those for MSRV reasons.

Allow `clippy::transmute_float_to_int` in MSRV compat functions

---

src/tree/taffy_tree.rs

Profiling Taffy tree and seeing what kind of TaffyTree methods would be useful for `egui_taffy`, added missing inline attributes where some branchs could be optimized away.  During https://github.com/DioxusLabs/taffy/issues/800
Additional function is added to TaffyTree, can still be released in patch release. Would be useful for `egui_taffy`.

Inlining and additional helper function for TaffyTree

---

examples/custom_tree_owned_partial.rs
examples/custom_tree_owned_unsafe.rs
examples/custom_tree_vec.rs
src/tree/cache.rs
src/tree/mod.rs
src/tree/taffy_tree.rs

Fixes https://github.com/DioxusLabs/taffy/issues/800
Mark if cache has been cleared. It should hold true that if node is dirty(cleared) then all ancestors of it are dirty(cleared) too and therefore all ancestors do not need to be visited repeatedly.
Cache is used in other structures too and I am not 100% sure that assumption holds and is correctly updated during layout calculations.  (See hidden elements, but for them this should still be correct due to sub-tree being hidden).
Feel free to edit branch if minor fixes are needed.

TaffyTree mark_dirty optimization

---

Cargo.toml
benches/Cargo.toml
examples/custom_tree_owned_partial.rs
examples/custom_tree_owned_unsafe.rs
examples/custom_tree_vec.rs
src/compute/grid/explicit_grid.rs
src/compute/grid/track_sizing.rs
src/compute/grid/types/grid_item.rs
src/compute/leaf.rs
src/style/compact_length.rs
src/style/dimension.rs
src/style/grid.rs
src/tree/taffy_tree.rs
src/tree/traits.rs
src/util/resolve.rs

- Enable the `CompactLength` abstraction to work with strict pointer provenance
- Enable the `CompactLength` abstraction to work on 32 bit platforms
This PR intentionally breaks serde serialization for Calc values (which previously existed but were broken): attempting to serialize or deserialize a calc value with cause serde to return an `Err`. This is because there is no sensible serialization given the type erasure scheme we are using. The ability to serialize Calc values with user-provided serialization and deserialization methods may be added in future.

Use `*const ()` to represent `CompactLength` and add implementation for 32 bit platforms

---

src/style/compact_length.rs
src/style/dimension.rs
src/style/grid.rs

- `CompactLength` and other length representations rely on values with invalid tags never been constructed. This PR enforces that invariant for values constructed via serde deserialization.

Validate tag when deserializing values

---

.github/workflows/ci.yml
Cargo.toml
src/compute/grid/track_sizing.rs
src/style/compact_length.rs
src/style/dimension.rs
src/style/grid.rs
src/tree/traits.rs
src/util/resolve.rs

Following our usual "pay for what you use" philosophy, this allows `calc()` to be disabled.

Feature flag calc values

---

examples/cosmic_text/src/main.rs

Fix clippy::large_enum_variant lint in cosmic-text example

---

src/style/mod.rs

Fix `BoxSizing::ContentBox` being described as "border box" and `BoxSizing::BorderBox` being described as "content box".

Fix `style::BoxSizing` comment

---

.github/workflows/ci.yml
.gitignore
Cargo.toml
examples/cosmic_text/Cargo.toml

Upgrade cosmic-text dependency used in our cosmic-text example to the latest version
I had the remove the example's crate from the main workspace as otherwise it breaks the MSRV compile for the main `taffy` crate.

Upgrade cosmic-text to 0.13

---

src/compute/grid/placement.rs
test_fixtures/grid/grid_placement_definite_primary.html
tests/generated/grid/grid_placement_definite_primary.rs
tests/generated/grid/mod.rs

This fixes a case where a grid item on the primary axis would get put into a wrong track.
This came up in this issue https://github.com/DioxusLabs/blitz/issues/187
Where a gird looked like this
(with commit)

fix: removed wrong addition, causing items to be misplaced.

---

src/compute/leaf.rs

Fixes issue where a max size can cause a leaf element to become oversized.
- Fixes the desktop layout of servo.org (https://github.com/DioxusLabs/blitz/issues/194)

Leaf layout: don't set indefinite available space to max-size

---

src/compute/mod.rs
src/style/mod.rs

The `DetailedGridTracksInfo` struct was previously public but not exported from a public module which makes it difficult to access and means that it wasn't properly documented.

Doc: ensure detailed grid info types are public / documented

---

CHANGELOG.md
Cargo.toml

Update version number and changelog for 0.8.0 release.

Prepare for 0.8.0 release

---

src/compute/grid/types/cell_occupancy.rs

- Ensure correctness when automatically placing grid items.

Fix: Calculate correct new grid size when expanding cell_occupancy_matrix in the negative direction

---

.github/workflows/ci.yml
src/style/compact_length.rs

- Fix compilation on 32bit targets with the `serde` feature enabled
- Add CI check to prevent future regressions on 32bit targets
Failed Servo CI build:
- https://github.com/servo/servo/actions/runs/15518902310/job/43689449782

Fix serde feature on 32bit targets

---

CHANGELOG.md

In the 0.9 section of the changelog, it looks like `NonRepeatingTrackSizingFunction` should be  `NonRepeatedTrackSizingFunction`

Fix mistake in 0.9 changelog
