DioxusLabs/taffy

- .github/workflows/ci.yml
- benches/complex.rs
- src/style.rs
Add basic CI with jobs from https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md.
Also fixes some small format/clippy issues
> Setup basic ci

- bindings/swift/StretchCore/Cargo.toml
- bindings/swift/StretchCore/src/lib.rs
- bindings/swift/StretchKit/Headers/libstretch.h
fixes #5 
`/bindings/swift/install_libraries.sh` wasn't working properly anymore (to be fair it's not working in the [original stretch](https://github.com/vislyhq/stretch) repo either)
> fixed swift bindings

- RELEASES.md
- Fixes #31
- Add a basic release notes file
- Capture functional changes since the final release of `stretch`.
> Add release notes

- .github/dependabot.yml
Fixes #64 
Copied the file from Bevy's dependabot setup here: https://github.com/bevyengine/bevy/blob/main/.github/dependabot.yml but not quite sure what labels (if any) we'd want dependabot to use as label. 
Thoughts?
> Setup and enable dependabot

- src/node.rs
Fixes #109
This should be relatively uncontroversial and internal change, not needing a note in `Releases`
> Cleanup arguments

- src/indexmap.rs
I messed this up trying to do it manually in #91. Oops!
> Fix #[allow(dead_code)] annotation

- Cargo.toml
- RELEASES.md
To prepare for new and upcoming changes :)
> Bump releases to `0.2.0`

- src/flexbox.rs
We seem to have left some doc comments dangling / half-finished. This cleans that up.
Let me know if the wording needs some adjustment
> Minor docs fix in `flexbox.rs`

- src/node.rs
I made a typo in #157, which was spotted by @SkyFire13. Thanks!
> Correctly test that MeasureFunc is Send and Sync

- src/geometry.rs
[As mentioned here](https://github.com/DioxusLabs/taffy/pull/174#issuecomment-1159283089), nightly clippy got some new lints. This fixes those.
> Fix new clippy lints

- RELEASES.md
- src/flexbox.rs
- src/layout.rs
> Move `hidden_layout()` to parent scope

- src/flexbox.rs
Fixes #200 
I'm not quite certain on how to properly test this as testing this would require fully testing the entire layout algorithm first, so I'm leaving it blank for now.
> Move flex-item and flex-line layout passes to methods instead of closures

- Cargo.toml
> Include readme in published package

- .github/workflows/ci.yml
> Prevent CI jobs from running twice on PRs

- benches/big_tree.rs
To better performance test deep trees.
See #243
> Add deeper depth benchmarks

- benches/big_tree.rs
- benches/complex.rs
Fixes benchmark compilation that was broken by #253
> Fix benchmark compilation + add super deep benchmarks

- src/tree.rs
> Improve wording and correctness of doc-comment

- .github/workflows/ci.yml
- Cargo.toml
- RELEASES.md
Update the release notes and package version number for the 0.2.1 release
> 0.2.1 release

- Cargo.toml
- RELEASES.md
- benches/big_tree.rs
Merge 0.2.2 changes into main (mainly changelog updates)
> Merge 0.2.2 into main

- tests/border_and_padding.rs
Fixes #286
Test checking the wrong values
None
> Fixing a test testing border instead of padding

- RELEASES.md
- Remove accidentally included property that isn't actually supported
- Fix MDN links
> Minor fixes to CSS Grid release notes

- benches/generated/gap_column_gap_percentage_flexible_with_padding.rs
- benches/generated/mod.rs
- test_fixtures/gap_column_gap_percentage_flexible_with_padding.html
- tests/generated/gap_column_gap_percentage_flexible_with_padding.rs
- tests/generated/mod.rs
Test for a case that wasn't previously covered by a test (but our code was already implementing correctly).
> Add test for flexbox gap in a container with padding

- src/compute/grid/mod.rs
Nightly has new lints again. Just a couple of minor fixes.
> Fix latest clippy lints

- docs/morphorm-style-properties.md
> Add morphorm style properties doc

- benches/generated/grid_placement_definite_in_secondary_axis_with_fully_definite_negative.rs
- tests/generated/grid_placement_definite_in_secondary_axis_with_fully_definite_negative.rs
A small change was made to one of the fixtures in a previous PR but the generated test wasn't properly updated.
> Fix generated tests being out of sync with fixtures

- benches/generated/grid_align_items_baseline_child_multiline_override.rs
- test_fixtures/grid_align_items_baseline_child_multiline_override.html
- tests/generated/grid_align_items_baseline_child_multiline_override.rs
> Update wrong css in test

- .github/workflows/ci.yml
- src/axis.rs
- src/compute/flexbox.rs
- src/compute/grid/mod.rs
- src/compute/grid/placement.rs
- src/compute/grid/track_sizing.rs
- src/geometry.rs
- src/layout.rs
- src/node.rs
- src/style/dimension.rs
- src/style/grid.rs
- src/style/mod.rs
- src/style_helpers.rs
> Fix `cargo doc` warnings + add `cargo doc` to CI

- Cargo.toml
- RELEASES.md
To make a small 0.3.1 release to fix #362
> Prepare for 0.3.1 release

- .github/workflows/ci.yml
- Cargo.toml
- RELEASES.md
- src/compute/grid/types/coordinates.rs
- src/geometry.rs
- src/style/grid.rs
Update 0.3.x branch with 0.3.1 changes
> Update 0.3.x branch with 0.3.1 changes

- Cargo.toml
- RELEASES.md
> Prepare for 0.3.2 release

- Cargo.toml
- RELEASES.md
- src/style/mod.rs
- src/style_helpers.rs
- tests/serde.rs
Merge v0.3.2 changes into 0.3.x branch
> Merge v0.3.2 changes into 0.3.x branch

- Cargo.toml
- RELEASES.md
To put out a release to fix
Blocked on #374  being merged
> Prepare for 0.3.3 release

- src/compute/grid/mod.rs
- tests/relayout.rs
Fix https://github.com/bevyengine/bevy/issues/7952
> Fix setting display:none on a grid child

- src/compute/flexbox.rs
> Fix new clippy lints (2023-03-09)

- src/compute/flexbox.rs
- src/geometry.rs
- test_fixtures/measure_child_with_min_size_greater_than_available_space.html
- tests/caching.rs
- tests/generated/measure_child_with_min_size_greater_than_available_space.rs
- tests/generated/mod.rs
Fixes #406
While this fixes the originally reported bug, I feel like there might be more related cases that aren't yet covered by tests. ~I'm also not sure if this is the best fix. It may be possible/better to move this fix to `leaf.rs`.~ EDIT: I tried this and was unable to make it work. I think the fix needs to be where it is.
> Fix: available space in the presence of a min width

- Cargo.toml
- RELEASES.md
Release notes and changelog for `v0.3.11`
> Prepare for 0.3.11 release

- Cargo.toml
- benches/flexbox.rs
Fix benchmark compilation with the `yoga_benchmark` feature enabled
> Fix yoga benchmarks

- Cargo.toml
- RELEASES.md
> Prepare for 0.3.12 release

- .github/workflows/ci.yml
Speed up CI.
https://blog.rust-lang.org/inside-rust/2023/01/30/cargo-sparse-protocol.html
> CI: use the cargo sparse index protocol

- benches/Cargo.toml
- benches/benches/flexbox.rs
- benches/benches/tree_creation.rs
- benches/src/lib.rs
Fix yoga benchmark feature flag
Feature flag was renamed in Cargo.toml but not in the code, causing it to have no effect
> Fix yoga benchmark feature flag

- src/style_helpers.rs
- I found discrepancy in docs :)
> Fixed comments in style_helpers.rs (Size -> Rect)

- RELEASES.md
Forgot to add changelog entries in #481
> Add changelog entries for grid placement fixes

- src/compute/grid/implicit_grid.rs
> minor misspelling fix (itme -> item)

- examples/basic.rs
> Fix commented out variant of basic example

- RELEASES.md
Update changelog on the `main` branch for 0.3.13
As the 0.3.x series has a release branch, release notes initially end up on that branch.
> Update main branch changelog for the v0.3.13 release

- Cargo.toml
- RELEASES.md
> Prepare for 0.3.14 release

- Cargo.toml
- RELEASES.md
- src/compute/mod.rs
- src/data.rs
Backport performance improvements from https://github.com/DioxusLabs/taffy/pull/556 to the 0.3.x series.
> Fix flex column performance (0.3.x backport)

- Cargo.toml
- RELEASES.md
- src/compute/flexbox.rs
- src/node.rs
> Release v0.3.17

- Cargo.toml
- RELEASES.md
- src/compute/flexbox.rs
- src/compute/grid/explicit_grid.rs
- src/compute/grid/mod.rs
- test_fixtures/bevy_issue_10343_flex.html
- test_fixtures/bevy_issue_10343_grid.html
- tests/generated/bevy_issue_10343_flex.rs
- tests/generated/bevy_issue_10343_grid.rs
- tests/generated/mod.rs
Prepare for 0.3.18 release:
- Cherry pick #576 
- Update release notes
> Release v0.3.18

- RELEASES.md
Ensure that the main branch has the latest release notes for backported versions.
> Copy 0.3.17 and 0.3.18 release notes to main

- src/compute/flexbox.rs
- src/compute/grid/explicit_grid.rs
Fix clippy lints
- https://github.com/DioxusLabs/taffy/pull/592 is failing CI due to unrelated clippy lints
> Fix clippy::ptr_arg lints

- src/lib.rs
> Fix docs copy-paste error

- src/compute/mod.rs
- src/lib.rs
- src/tree/traits.rs
- Fixes #429 
Taffy's low-level API was entirely lacking in documentation. This is a first stab at it.
This is a bit WIP (although it probably could be merged as-is - better than nothing!), but @alice-i-cecile was discussing writing some herself, so I thought I would publish what I had.
- Any feedback on the documentation itself is welcome.
> Document low-level traits

- Cargo.toml
Give myself credit for working on Taffy
https://github.com/DioxusLabs/taffy/pulls?q=is%3Apr+is%3Aclosed+author%3Anicoburns
Can I add myself to the list?
> Add Nico Burns to the authors list

- src/compute/flexbox.rs
- src/compute/grid/placement.rs
- src/tree/cache.rs
- src/tree/layout.rs
- src/tree/taffy_tree.rs
> Fix clippy lints (2024-03)

- Cargo.toml
- RELEASES.md
Update version number and release notes for v0.4.1 release.
> Prepare for v0.4.1 release

- Cargo.toml
- RELEASES.md
Update version number and release notes for `v0.5.0` release.
> Prepare for v0.5.0 release

- Cargo.toml
- RELEASES.md
Update version number and release notes for v0.5.1 release
> Prepare for v0.5.1 release

- Cargo.toml
- examples/cosmic_text.rs
- Ensures that example uses the latest cosmic-text version.
- Closes #669
> Update cosmic-text example to cosmic-text 0.12

- src/compute/block.rs
Make the code read a little clearer
> Make it clearer which state is mutable in block layout abspos implementation

- src/style/dimension.rs
- src/tree/cache.rs
- src/tree/layout.rs
The serde feature should cover all useful types.
> Increase coverage of serde derives

- examples/cosmic_text.rs
- examples/custom_tree_owned_partial.rs
- examples/custom_tree_owned_unsafe.rs
- src/compute/mod.rs
- src/style/flex.rs
- src/style_helpers.rs
- src/tree/taffy_tree.rs
Fixes clippy lints that were failing
> fix: clippy lints

- benches/benches/tree_creation.rs
- examples/custom_tree_owned_unsafe.rs
- examples/custom_tree_vec.rs
- scripts/gentest/src/main.rs
- src/compute/grid/track_sizing.rs
- src/style/grid.rs
- src/tree/taffy_tree.rs
> Fix clippy lints (2024-10-10)

- src/tree/taffy_tree.rs
> Fix documentation of dirty and mark_dirty functions

- .github/workflows/ci.yml
Speed up CI by parallelising building examples (which can be slow due to dependencies)
> Build examples separately in CI

- Cargo.toml
- RELEASES.md
Update version number and release notes for v0.6.1 release
> Prepare for 0.6.1 release

- .gitignore
- scripts/gentest/src/main.rs
- src/compute/grid/mod.rs
Create a space for "messing around" with gentest like files without them needing to become part of the repo.
Also includes a couple of clippy lint fixes to make CI happy.
> Add `test_fixtures/_scratch` dir to gitignore

- .github/workflows/ci.yml
> Fixup CI for cargo alias changes

- src/compute/flexbox.rs
- test_fixtures/flex/bevy_issue_16304.html
- tests/generated/flex/bevy_issue_16304.rs
- tests/generated/flex/mod.rs
> Flexbox: clamp indefinite available space by min- and max- size as appropriate

- Cargo.toml
- RELEASES.md
Update changelog and release notes for v0.6.2 release
> Prepare for v0.6.2 release

- CHANGELOG.md
`CHANGELOG.md` is the conventional name for this file. Let's use it.
> Rename RELEASES.md to CHANGELOG.md

- justfile
Allows extra parameters to be passed to `just bench`
> Add params to bench justfile task

- CHANGELOG.md
- Cargo.toml
Update changelog and release notes for v0.6.3 release
> Prepare for v0.6.3 release

- CHANGELOG.md
- Cargo.toml
- benches/benches/flexbox.rs
- benches/src/taffy_helpers.rs
Update version number and changelog for `v0.7.0` release
> Prepare for v0.7.0 release

- src/util/sys.rs
Reduce dependencies. This PR inlines the 3 functions we use from `num-traits`.
- We only use 3 functions from `num-traits`
- We only use `num-traits` when not targeting std.
> Eliminate the `num-traits` dependency

- Cargo.toml
- src/compute/grid/explicit_grid.rs
- src/util/sys.rs
- #761 missed one use of num-traits
- #761 didn't actually remove num-traits from Cargo.toml
> Fully remove num-traits

- CHANGELOG.md
- Cargo.toml
Update version number and changelog for `v0.7.1` release
> Prepare for v0.7.1 release

- .github/workflows/ci.yml
- src/lib.rs
- src/tree/layout.rs
- src/tree/taffy_tree.rs
- src/tree/traits.rs
- Some small tweaks and cleanups to https://github.com/DioxusLabs/taffy/pull/772 before we publish
> Detailed layout info cleanup

- src/lib.rs
- src/style/mod.rs
Just fixes some super tiny docs issues I noticed. Missing word in `Style` docs and broken link.
> Minor Docs Fixes

- CHANGELOG.md
- Cargo.toml
Update version number and changelog for v0.7.3 release
> Prepare for v0.7.3 release

- benches/Cargo.toml
- benches/src/yoga_helpers.rs
- Fix our build. The old version of yoga-rs started failing on newer Github Actions runners.
- Upgrade to the latest version of Yoga for fair benchmarks
> Upgrade `yoga-rs` (benchmark dependency) to v0.5.0

- benches/Cargo.toml
- benches/benches/flexbox.rs
- benches/benches/grid.rs
- benches/benches/tree_creation.rs
- benches/src/lib.rs
- benches/src/taffy_03_helpers.rs
- benches/src/taffy_helpers.rs
- benches/src/yoga_helpers.rs
- src/compute/flexbox.rs
- src/tree/traits.rs
- Keep rand deps up to date.
- Fixes some unrelated clippy lints in order to be mergeable.
> Upgrade rand and rand_chacha (bench deps) to 0.9

- src/compute/grid/placement.rs
This grid placement code had the axes mixed up
- Builds on https://github.com/DioxusLabs/taffy/pull/817
> Fix grid placement for items with fixed primary axis

- CHANGELOG.md
- Cargo.toml
Update version number and changelog for `v0.8.1` release
> Prepare for v0.8.1 release

- scripts/gentest/src/main.rs
- src/style/compact_length.rs
Fix clippy lints for latest Rust versions
> Fix clippy lints (May 2025)

- CHANGELOG.md
- Cargo.toml
- benches/src/taffy_helpers.rs
Update changelog and version number for `v0.9.0` release
> Prepare for v0.9.0 release
